import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import {
  SOUND_IDS_V1,
  SOUND_MANIFEST_V1,
} from "../../src/audio/sound-manifest";
import {
  STOCK_SOUND_GENERATED_V1,
  STOCK_SOUNDS_V1,
  stockSoundV1,
  type StockSoundCandidateV1,
  type StockSoundV1,
} from "../../src/audio/stock-sounds";

/**
 * Writes `docs/audio/STOCK_SOUND_CHOICES.md` from the provenance manifest
 * `src/audio/stock-sounds.json` (bead pulp_wars-2yc.24, docs/ui/SOUND.md
 * "Choosing between recordings"): every game sound with its status, the
 * recordings it can play and what was measured of each, and the sounds a
 * person should listen to first. The document is never edited by hand:
 *
 *   npm run audio:stock-sound-choices -- render   rewrite the document
 *   npm run audio:stock-sound-choices -- check    fail when it is out of date
 *
 * It reads no library file and writes no audio.
 */

const ROOT = resolve(fileURLToPath(import.meta.url), "../../..");
export const STOCK_SOUND_CHOICES_DOC_PATH = resolve(
  ROOT,
  "docs/audio/STOCK_SOUND_CHOICES.md",
);

/** The four things a game sound can be, as the document says them. */
export type StockSoundStatusV1 =
  "RECORDED_SINGLE" | "RECORDED_OPTIONS" | "GENERATED_OPTIONS" | "GENERATED";

export interface StockSoundStatusRowV1 {
  readonly id: string;
  readonly label: string;
  readonly status: StockSoundStatusV1;
  /** How many recordings it has. */
  readonly candidates: number;
  /** The default candidate's number; 0 when the default is generated. */
  readonly default: number;
}

/** One row per game sound, in the manifest's order. */
export function stockSoundStatusRowsV1(): readonly StockSoundStatusRowV1[] {
  return SOUND_IDS_V1.map((id) => {
    const sound = stockSoundV1(id);
    const candidates = sound?.candidates.length ?? 0;
    const status: StockSoundStatusV1 =
      sound === null
        ? "GENERATED"
        : sound.default === 0
          ? "GENERATED_OPTIONS"
          : candidates === 1
            ? "RECORDED_SINGLE"
            : "RECORDED_OPTIONS";
    return {
      id,
      label: SOUND_MANIFEST_V1[id].label,
      status,
      candidates,
      default: sound?.default ?? 0,
    };
  });
}

/** A status in words: "Recorded — 3 options awaiting your pick". */
export function stockSoundStatusTextV1(row: StockSoundStatusRowV1): string {
  switch (row.status) {
    case "RECORDED_SINGLE":
      return "Recorded — single option";
    case "RECORDED_OPTIONS":
      return `Recorded — ${row.candidates} options awaiting your pick`;
    case "GENERATED_OPTIONS":
      return row.candidates === 1
        ? "Generated — 1 recording to compare"
        : `Generated — ${row.candidates} recordings to compare`;
    case "GENERATED":
      return "Generated — no recording fits";
  }
}

/** Text for a table cell: no pipes, no line breaks. */
function cell(text: string): string {
  return text.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}

function seconds(value: number): string {
  return String(Number(value.toFixed(3)));
}

function sourceOf(candidate: StockSoundCandidateV1): string {
  return `${candidate.library} / \`${candidate.originalFile}\``;
}

function defaultText(sound: StockSoundV1): string {
  if (sound.default === 0) return "Generated";
  const candidate = sound.candidates.find((entry) => entry.n === sound.default);
  return candidate === undefined
    ? "Generated"
    : `#${candidate.n}: part ${candidate.part}, ${sourceOf(candidate)}`;
}

/** The document, before Prettier lays out its tables. */
export function stockSoundChoicesMarkdownV1(): string {
  const rows = stockSoundStatusRowsV1();
  const count = (status: StockSoundStatusV1): number =>
    rows.filter((row) => row.status === status).length;
  const clips = STOCK_SOUNDS_V1.reduce(
    (sum, sound) => sum + sound.candidates.length,
    0,
  );
  const lines: string[] = [
    "# Stock sound choices",
    "",
    "<!-- Generated by scripts/audio/stock-sound-choices.ts from src/audio/stock-sounds.json. Do not edit by hand: change the manifest and run `npm run audio:stock-sound-choices -- render`. -->",
    "",
    "Which recording each game sound plays, which other recordings it could",
    "play, and which sounds are still generated. Bead `pulp_wars-2yc.24`; the",
    "rules, the licence and the tools are in",
    "[docs/ui/SOUND.md](../ui/SOUND.md#stock-recordings).",
    "",
    "Nobody listened to any of these while choosing. Every choice was made",
    "from file names and measurements, and the note beside a recording says",
    "what was measured, not what it sounds like. That is why a sound with",
    "more than one plausible recording keeps them all: the choice is yours.",
    "",
    "## How to choose",
    "",
    "1. Open the Gallery and its **Sounds** tab. A sound with recordings has a",
    "   numbered row under its card, one line a recording, and **Generated**",
    "   last.",
    "2. Press a line to hear it. Press **Use** on the one you like: the game",
    "   plays it from then on, in that browser only.",
    "3. Press **Copy my picks** at the top of the tab and paste the text to",
    "   the developer. The default everyone gets changes only when",
    "   `src/audio/stock-sounds.json` does.",
    "",
    "A number below is the recording's number in that row.",
    "",
    "## The count",
    "",
    `- ${rows.length} game sounds.`,
    `- ${count("RECORDED_SINGLE") + count("RECORDED_OPTIONS")} play a recording by default: ${count("RECORDED_OPTIONS")} have several to choose from, ${count("RECORDED_SINGLE")} have one.`,
    `- ${count("GENERATED_OPTIONS")} are generated by default and have recordings to compare with: none of those recordings is a clear match, so none replaces the generated sound until you pick it.`,
    `- ${count("GENERATED")} are generated and have no recording: the bundle has nothing that fits.`,
    `- ${clips} clips in the repository.`,
    "",
    "## Listen to these first",
    "",
    "The sounds that play a recording by default and whose match is the",
    "least certain, in the order the Gallery shows them.",
    "",
    "| Sound | Plays by default | Why first |",
    "| --- | --- | --- |",
  ];
  for (const sound of STOCK_SOUNDS_V1) {
    if (sound.listenFirst === undefined) continue;
    lines.push(
      `| \`${sound.id}\` | ${cell(defaultText(sound))} | ${cell(sound.listenFirst)} |`,
    );
  }
  lines.push(
    "",
    "## Every sound",
    "",
    "| Sound | Name | Status | Plays by default | Confidence |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const row of rows) {
    const sound = stockSoundV1(row.id);
    lines.push(
      `| \`${row.id}\` | ${cell(row.label)} | ${stockSoundStatusTextV1(row)} | ${
        sound === null ? "Generated" : cell(defaultText(sound))
      } | ${sound === null ? "" : sound.confidence} |`,
    );
  }
  lines.push(
    "",
    "## The recordings",
    "",
    "For each sound that has any: why these, then one line a recording. The",
    'cut is the stretch of the original file in seconds; "level" is the',
    "clip's `gain` in the mix.",
  );
  for (const sound of STOCK_SOUNDS_V1) {
    const row = rows.find((entry) => entry.id === sound.id);
    lines.push(
      "",
      `### \`${sound.id}\` — ${row?.label ?? sound.id}`,
      "",
      `${row === undefined ? "" : `${stockSoundStatusTextV1(row)}. `}${sound.why}`,
      "",
      "| # | Default | Part | Library / original file | Cut | Level | What was measured |",
      "| --- | --- | --- | --- | --- | --- | --- |",
    );
    for (const candidate of sound.candidates)
      lines.push(
        `| ${candidate.n} | ${candidate.n === sound.default ? "yes" : ""} | ${candidate.part} | ${cell(sourceOf(candidate))} | ${seconds(candidate.startSeconds)}–${seconds(candidate.endSeconds)} | ${candidate.gain} | ${cell(`${candidate.note} ${candidate.take}`)} |`,
      );
    lines.push(
      `| Generated | ${sound.default === 0 ? "yes" : ""} |  | The synthesised sound |  |  | Always there: it plays until a clip has loaded, and it can be picked. |`,
    );
  }
  lines.push(
    "",
    "## Still generated",
    "",
    "What was looked for and not found, and the kind of recording that would",
    "serve: the list to check another sound library against.",
    "",
    "| Sound | Name | Why nothing was taken | A recording that would serve |",
    "| --- | --- | --- | --- |",
  );
  for (const entry of STOCK_SOUND_GENERATED_V1) {
    const row = rows.find((candidate) => candidate.id === entry.id);
    lines.push(
      `| \`${entry.id}\` | ${cell(row?.label ?? "")} | ${cell(entry.why)} | ${cell(entry.wanted)} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

/** The document as it is checked in: laid out by Prettier. */
export async function renderStockSoundChoicesV1(): Promise<string> {
  return format(stockSoundChoicesMarkdownV1(), {
    parser: "markdown",
    proseWrap: "preserve",
  });
}

async function main(command: string | undefined): Promise<number> {
  if (command !== "render" && command !== "check") {
    process.stderr.write("Usage: stock-sound-choices.ts <render|check>\n");
    return 2;
  }
  const text = await renderStockSoundChoicesV1();
  if (command === "render") {
    await writeFile(STOCK_SOUND_CHOICES_DOC_PATH, text);
    process.stdout.write(`Wrote ${STOCK_SOUND_CHOICES_DOC_PATH}\n`);
    return 0;
  }
  const current = await readFile(STOCK_SOUND_CHOICES_DOC_PATH, "utf8").catch(
    () => "",
  );
  if (current === text) return 0;
  process.stderr.write(
    "docs/audio/STOCK_SOUND_CHOICES.md is out of date: run `npm run audio:stock-sound-choices -- render`.\n",
  );
  return 1;
}

if (process.argv[1]?.endsWith("stock-sound-choices.ts") === true)
  void main(process.argv[2]).then((code) => {
    process.exitCode = code;
  });
