import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import {
  FACTION_DISPLAY_NAMES_V7,
  FACTION_IDS_V7,
} from "../../src/engine/index";

/**
 * The faction theme prompts (bead pulp_wars-2yc.21, docs/audio/THEME_MUSIC.md).
 *
 * `docs/audio/theme-prompts.json` is the source of truth for the text the
 * user pastes into a music service. This script validates it against the
 * game's factions and renders it into the marked section of the document,
 * so the two cannot drift:
 *
 *   npm run audio:theme-prompts -- check    validate, and compare the document
 *   npm run audio:theme-prompts -- render   rewrite the document's section
 *
 * It calls no service and writes no audio.
 */

const ROOT = resolve(fileURLToPath(import.meta.url), "../../..");
export const THEME_PROMPTS_DATA_PATH = resolve(
  ROOT,
  "docs/audio/theme-prompts.json",
);
export const THEME_MUSIC_DOC_PATH = resolve(ROOT, "docs/audio/THEME_MUSIC.md");

export const THEME_PROMPTS_SCHEMA_VERSION = 1;
export const THEME_SECTION_BEGIN =
  "<!-- theme-prompts:begin (generated by scripts/audio/theme-prompts.ts from theme-prompts.json; do not edit by hand) -->";
export const THEME_SECTION_END = "<!-- theme-prompts:end -->";

export interface ThemeTempoV1 {
  readonly min: number;
  readonly max: number;
  readonly target: number;
  /** The note that gets the beat: "quarter", or "dotted quarter" in 6/8. */
  readonly beat: string;
}

export interface ThemeMetreV1 {
  readonly signature: string;
  readonly feel: string;
}

export interface ThemeSharedV1 {
  /** Bumped when a shared fragment below changes. */
  readonly version: number;
  readonly budgets: {
    readonly sunoStyleChars: number;
    readonly sunoExcludeChars: number;
    readonly longPromptChars: number;
  };
  readonly length: {
    readonly targetSeconds: number;
    readonly minSeconds: number;
    readonly maxSeconds: number;
  };
  readonly outputFilePattern: string;
  /** The opening figure every theme shares; every long prompt names it. */
  readonly motif: string;
  /** Appended to every faction's Suno style tags. */
  readonly sunoCommonStyle: string;
  /** Prepended to every faction's Suno exclude tags. */
  readonly sunoCommonExclude: string;
  /** The one sentence that may name vocals: it forbids them. */
  readonly instrumentalSentence: string;
  /** Appended to every faction's long prompt after that sentence. */
  readonly longPromptTail: string;
}

export interface ThemeFactionPromptV1 {
  /** The player-facing faction name, as the game shows it. */
  readonly name: string;
  readonly themeId: string;
  readonly outputFile: string;
  /** Bumped when any prompt text of this entry changes. */
  readonly promptVersion: number;
  readonly identity: string;
  readonly palette: {
    readonly lead: readonly string[];
    readonly rhythm: readonly string[];
    readonly colour: readonly string[];
  };
  readonly tempo: ThemeTempoV1;
  readonly metre: ThemeMetreV1;
  readonly mode: string;
  readonly mood: readonly string[];
  /** The faction's own tags; `sunoStyleV1` adds the shared ones. */
  readonly sunoStyle: string;
  /** Bracketed section tags, one per line, with no words outside brackets. */
  readonly sunoStructure: readonly string[];
  /** The faction's own exclusions; `sunoExcludeV1` adds the shared ones. */
  readonly sunoExclude: string;
  /** The faction's own paragraph; `longPromptV1` adds the shared ending. */
  readonly longPrompt: string;
}

/** A title theme or a stinger: its strings are complete as stored. */
export interface ThemeExtraPromptV1 {
  readonly id: string;
  readonly name: string;
  readonly use: string;
  readonly outputFile: string;
  readonly loop: boolean;
  readonly durationSeconds: number;
  readonly promptVersion: number;
  readonly tempo: ThemeTempoV1;
  readonly metre: ThemeMetreV1;
  readonly sunoStyle: string;
  readonly sunoStructure: readonly string[];
  readonly sunoExclude: string;
  readonly longPrompt: string;
}

export interface ThemePromptsV1 {
  readonly schemaVersion: number;
  readonly shared: ThemeSharedV1;
  readonly factions: Readonly<Record<string, ThemeFactionPromptV1>>;
  readonly extras: readonly ThemeExtraPromptV1[];
}

/** A faction of the game: its id and the name the player reads. */
export interface ThemeFactionV1 {
  readonly id: string;
  readonly name: string;
}

/** The factions the game has today, from the engine. */
export const GAME_THEME_FACTIONS_V1: readonly ThemeFactionV1[] =
  FACTION_IDS_V7.map((id) => ({ id, name: FACTION_DISPLAY_NAMES_V7[id] }));

export async function loadThemePromptsV1(): Promise<ThemePromptsV1> {
  return JSON.parse(
    await readFile(THEME_PROMPTS_DATA_PATH, "utf8"),
  ) as ThemePromptsV1;
}

/** The text for Suno's style field: the faction's tags, then the shared. */
export function sunoStyleV1(
  shared: ThemeSharedV1,
  entry: ThemeFactionPromptV1,
): string {
  return `${entry.sunoStyle}, ${shared.sunoCommonStyle}`;
}

/** The text for Suno's exclude field: the shared tags, then the faction's. */
export function sunoExcludeV1(
  shared: ThemeSharedV1,
  entry: ThemeFactionPromptV1,
): string {
  return `${shared.sunoCommonExclude}, ${entry.sunoExclude}`;
}

/** The one-paragraph prompt for a service that takes a description. */
export function longPromptV1(
  shared: ThemeSharedV1,
  entry: ThemeFactionPromptV1,
): string {
  return `${entry.longPrompt} ${shared.instrumentalSentence} ${shared.longPromptTail}`;
}

/** What a generation record cites: "UNDEAD@1+s1". */
export function promptVersionIdV1(
  shared: ThemeSharedV1,
  key: string,
  promptVersion: number,
): string {
  return `${key}@${promptVersion}+s${shared.version}`;
}

/** "ICE_FOLK" names its theme "ice-folk", from the player-facing name. */
export function themeNameV1(displayName: string): string {
  return displayName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

/**
 * Words that ask for a voice. No style string, structure block or long
 * prompt may contain one, except inside the shared sentence that forbids
 * them. Exclude strings are exempt: that is where these words belong.
 */
export const THEME_VOCAL_WORDS_V1: readonly string[] = [
  "vocal",
  "vocals",
  "vocalist",
  "voice",
  "voices",
  "sing",
  "sings",
  "singing",
  "singer",
  "singers",
  "sung",
  "choir",
  "choirs",
  "choral",
  "chorus",
  "chant",
  "chants",
  "chanting",
  "lyric",
  "lyrics",
  "rap",
  "rapping",
  "spoken",
  "narration",
  "narrator",
  "hum",
  "humming",
  "scat",
  "a cappella",
  "acapella",
  "yodel",
  "yodelling",
  "shout",
  "shouts",
  "shouting",
  "whisper",
  "whispers",
  "whispering",
];

/**
 * Phrases that ask a service to imitate something. Services reject or
 * mishandle them, and the game wants its own sound.
 */
export const THEME_IMITATION_PHRASES_V1: readonly string[] = [
  "in the style of",
  "style of",
  "inspired by",
  "sounds like",
  "sound like",
  "similar to",
  "reminiscent of",
  "theme from",
  "soundtrack of",
  "soundtrack to",
  "cartoon",
  "tv show",
  "tv series",
  "anime",
];

/**
 * Names that must never reach a prompt: composers, bands and franchises a
 * writer might reach for when describing these factions. It is a guard for
 * the obvious ones, not a complete list; the rule in the document is "no
 * proper names at all". Add the obvious names for a new faction's genre
 * when adding the faction.
 */
export const THEME_NAME_DENYLIST_V1: readonly string[] = [
  // Composers and performers.
  "john williams",
  "hans zimmer",
  "zimmer",
  "danny elfman",
  "elfman",
  "tim burton",
  "burton",
  "ennio morricone",
  "morricone",
  "bernard herrmann",
  "herrmann",
  "howard shore",
  "koji kondo",
  "nobuo uematsu",
  "uematsu",
  "jeremy soule",
  "grant kirkhope",
  "kirkhope",
  "raymond scott",
  "esquivel",
  "les baxter",
  "mancini",
  "spike jones",
  "sousa",
  "saint-saens",
  "saint-saëns",
  "danse macabre",
  "grieg",
  "mountain king",
  "wagner",
  "valkyries",
  "tchaikovsky",
  "nutcracker",
  "sugar plum",
  "mussorgsky",
  "holst",
  "strauss",
  // Strategy and fantasy games.
  "polytopia",
  "civilization",
  "age of empires",
  "warcraft",
  "warhammer",
  "heroes of might and magic",
  "zelda",
  "mario",
  "nintendo",
  "pokemon",
  "final fantasy",
  "minecraft",
  "skyrim",
  "elder scrolls",
  "banjo-kazooie",
  "katamari",
  "plants vs",
  "dwarf fortress",
  "deep rock",
  "bioshock",
  // Fantasy, horror-comedy and science-fiction franchises.
  "lord of the rings",
  "hobbit",
  "tolkien",
  "game of thrones",
  "harry potter",
  "monty python",
  "nightmare before christmas",
  "addams",
  "beetlejuice",
  "ghostbusters",
  "haunted mansion",
  "star wars",
  "star trek",
  "doctor who",
  "mars attacks",
  "war of the worlds",
  "forbidden planet",
  "twilight zone",
  "the day the earth stood still",
  "jetsons",
  "futurama",
  "jurassic",
  "flintstones",
  "land before time",
  "snow white",
  "heigh-ho",
  "steamboy",
  // Studios and sweet-themed properties.
  "disney",
  "pixar",
  "dreamworks",
  "looney tunes",
  "merrie melodies",
  "willy wonka",
  "wonka",
  "candy crush",
  "candy land",
  "candyland",
  "candy kingdom",
  "wreck-it",
  "my little pony",
];

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** The entries of `words` that occur in `text` as whole words. */
export function wordsFoundV1(text: string, words: readonly string[]): string[] {
  const lower = text.toLowerCase();
  return words.filter((word) =>
    new RegExp(
      `(?<![\\p{L}\\p{N}])${escapeRegExp(word)}(?![\\p{L}\\p{N}])`,
      "u",
    ).test(lower),
  );
}

interface PromptTextsV1 {
  readonly label: string;
  readonly style: string;
  readonly structure: readonly string[];
  readonly exclude: string;
  readonly long: string;
  readonly tempo: ThemeTempoV1;
  readonly promptVersion: number;
}

function checkPromptTexts(
  shared: ThemeSharedV1,
  texts: PromptTextsV1,
  problems: string[],
): void {
  const { label } = texts;
  const { budgets } = shared;
  if (texts.style.length > budgets.sunoStyleChars) {
    problems.push(
      `${label}: the Suno style string is ${texts.style.length} characters, over the budget of ${budgets.sunoStyleChars}`,
    );
  }
  if (texts.exclude.length > budgets.sunoExcludeChars) {
    problems.push(
      `${label}: the Suno exclude string is ${texts.exclude.length} characters, over the budget of ${budgets.sunoExcludeChars}`,
    );
  }
  if (texts.long.length > budgets.longPromptChars) {
    problems.push(
      `${label}: the long prompt is ${texts.long.length} characters, over the budget of ${budgets.longPromptChars}`,
    );
  }
  if (texts.style.trim() === "" || texts.long.trim() === "") {
    problems.push(`${label}: a prompt is empty`);
  }
  if (!/(^|, )instrumental(,|$)/.test(texts.style)) {
    problems.push(
      `${label}: the Suno style string lacks the tag "instrumental"`,
    );
  }
  if (!/(^|, )vocals(,|$)/.test(texts.exclude)) {
    problems.push(`${label}: the Suno exclude string lacks the tag "vocals"`);
  }
  if (!texts.long.includes(shared.instrumentalSentence)) {
    problems.push(
      `${label}: the long prompt lacks the sentence "${shared.instrumentalSentence}"`,
    );
  }
  if (/[\n\r]/.test(texts.long)) {
    problems.push(`${label}: the long prompt is not one paragraph`);
  }
  if (!texts.long.includes(shared.motif)) {
    problems.push(
      `${label}: the long prompt does not name the shared opening, "${shared.motif}"`,
    );
  }
  if (texts.structure.length === 0 || texts.structure[0] !== "[Instrumental]") {
    problems.push(
      `${label}: the structure block must start with the line [Instrumental]`,
    );
  }
  for (const line of texts.structure) {
    if (!/^\[[^[\]]+\]$/.test(line)) {
      problems.push(
        `${label}: the structure line "${line}" has text outside one pair of brackets (a service would sing it)`,
      );
    }
  }
  // The one sentence that forbids vocals is the only place they are named.
  const positive = [
    texts.style.replace(/(^|, )instrumental(?=,|$)/, ""),
    ...texts.structure.filter((line) => line !== "[Instrumental]"),
    texts.long.split(shared.instrumentalSentence).join(" "),
  ];
  const vocal = wordsFoundV1(positive.join("\n"), THEME_VOCAL_WORDS_V1);
  if (vocal.length > 0) {
    problems.push(
      `${label}: a prompt asks for a voice (${vocal.join(", ")}); describe instruments only`,
    );
  }
  const all = [texts.style, ...texts.structure, texts.exclude, texts.long].join(
    "\n",
  );
  const named = wordsFoundV1(all, THEME_NAME_DENYLIST_V1);
  if (named.length > 0) {
    problems.push(
      `${label}: a prompt names an artist or a franchise (${named.join(", ")}); describe the sound instead`,
    );
  }
  const imitation = wordsFoundV1(all, THEME_IMITATION_PHRASES_V1);
  if (imitation.length > 0) {
    problems.push(
      `${label}: a prompt asks for an imitation (${imitation.join(", ")}); describe the sound instead`,
    );
  }
  const { tempo } = texts;
  if (
    !(tempo.min <= tempo.target && tempo.target <= tempo.max) ||
    tempo.min <= 0
  ) {
    problems.push(`${label}: the tempo target is outside its range`);
  }
  if (!Number.isInteger(texts.promptVersion) || texts.promptVersion < 1) {
    problems.push(`${label}: promptVersion must be a whole number from 1`);
  }
}

/** The least two themes of one metre may differ by, in beats per minute. */
export const THEME_MIN_TEMPO_GAP_BPM_V1 = 10;

/**
 * Everything wrong with the data, as sentences; empty when it is sound.
 * `factions` is the game's list (a test passes another to prove the checks).
 */
export function validateThemePromptsV1(
  data: ThemePromptsV1,
  factions: readonly ThemeFactionV1[] = GAME_THEME_FACTIONS_V1,
): string[] {
  const problems: string[] = [];
  if (data.schemaVersion !== THEME_PROMPTS_SCHEMA_VERSION) {
    problems.push(
      `schemaVersion is ${String(data.schemaVersion)}, expected ${THEME_PROMPTS_SCHEMA_VERSION}`,
    );
  }
  const { shared } = data;
  if (!Number.isInteger(shared.version) || shared.version < 1) {
    problems.push("shared.version must be a whole number from 1");
  }
  if (
    !shared.longPromptTail.includes(`${shared.length.targetSeconds} seconds`)
  ) {
    problems.push(
      `shared.longPromptTail does not state the target length, "${shared.length.targetSeconds} seconds"`,
    );
  }
  const known = new Map(factions.map((faction) => [faction.id, faction]));
  for (const faction of factions) {
    if (data.factions[faction.id] === undefined) {
      problems.push(
        `${faction.id}: the faction exists in the game and has no theme prompt`,
      );
    }
  }
  const themeIds = new Set<string>();
  for (const [key, entry] of Object.entries(data.factions)) {
    const faction = known.get(key);
    if (faction === undefined) {
      problems.push(
        `${key}: a theme prompt for a faction the game does not have`,
      );
      continue;
    }
    if (entry.name !== faction.name) {
      problems.push(
        `${key}: the name "${entry.name}" is not the game's name, "${faction.name}"`,
      );
    }
    const name = themeNameV1(faction.name);
    if (entry.themeId !== `theme.${name}`) {
      problems.push(`${key}: the theme id must be "theme.${name}"`);
    }
    const file = shared.outputFilePattern.replace("<name>", name);
    if (entry.outputFile !== file) {
      problems.push(`${key}: the output file must be "${file}"`);
    }
    if (themeIds.has(entry.themeId)) {
      problems.push(`${key}: the theme id "${entry.themeId}" is used twice`);
    }
    themeIds.add(entry.themeId);
    for (const part of ["lead", "rhythm", "colour"] as const) {
      if (entry.palette[part].length === 0) {
        problems.push(`${key}: the palette has no ${part} instrument`);
      }
    }
    if (entry.mood.length === 0 || entry.identity.trim() === "") {
      problems.push(`${key}: the identity or the mood words are missing`);
    }
    checkPromptTexts(
      shared,
      {
        label: key,
        style: sunoStyleV1(shared, entry),
        structure: entry.sunoStructure,
        exclude: sunoExcludeV1(shared, entry),
        long: longPromptV1(shared, entry),
        tempo: entry.tempo,
        promptVersion: entry.promptVersion,
      },
      problems,
    );
  }
  // Two themes are never confused: same metre means clearly different tempo.
  const entries = Object.entries(data.factions);
  entries.forEach(([key, entry], index) => {
    for (const [otherKey, other] of entries.slice(index + 1)) {
      if (
        entry.metre.signature === other.metre.signature &&
        Math.abs(entry.tempo.target - other.tempo.target) <
          THEME_MIN_TEMPO_GAP_BPM_V1
      ) {
        problems.push(
          `${key} and ${otherKey}: both are in ${entry.metre.signature} and their tempos are less than ${THEME_MIN_TEMPO_GAP_BPM_V1} BPM apart`,
        );
      }
    }
  });
  const extraIds = new Set<string>();
  for (const extra of data.extras) {
    if (extraIds.has(extra.id) || themeIds.has(extra.id)) {
      problems.push(`${extra.id}: the id is used twice`);
    }
    extraIds.add(extra.id);
    checkPromptTexts(
      shared,
      {
        label: extra.id,
        style: extra.sunoStyle,
        structure: extra.sunoStructure,
        exclude: extra.sunoExclude,
        long: extra.longPrompt,
        tempo: extra.tempo,
        promptVersion: extra.promptVersion,
      },
      problems,
    );
  }
  return problems;
}

function beatsPerBar(signature: string): number {
  const [count, unit] = signature.split("/").map(Number);
  if (count === undefined || unit === undefined) return 4;
  // Compound time (6/8, 12/8) is counted in dotted beats.
  return unit === 8 && count % 3 === 0 ? count / 3 : count;
}

/**
 * A loop length near the target: a whole number of eight-bar phrases at the
 * target tempo.
 */
export function suggestedLoopV1(
  tempo: ThemeTempoV1,
  metre: ThemeMetreV1,
  targetSeconds: number,
): { readonly bars: number; readonly seconds: number } {
  const barSeconds = (beatsPerBar(metre.signature) * 60) / tempo.target;
  const bars = Math.max(8, Math.round(targetSeconds / barSeconds / 8) * 8);
  return { bars, seconds: Math.round(bars * barSeconds * 10) / 10 };
}

function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function table(header: readonly string[], rows: readonly string[][]): string {
  return [
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

function fence(text: string): string {
  return ["```text", text, "```"].join("\n");
}

function tempoText(tempo: ThemeTempoV1): string {
  const beat = tempo.beat === "quarter" ? "" : ` (${tempo.beat} beat)`;
  return `${tempo.target} BPM${beat}, accept ${tempo.min}–${tempo.max}`;
}

function promptBlocks(
  style: string,
  structure: readonly string[],
  exclude: string,
  long: string,
): string[] {
  return [
    `**Suno, style of music** (${style.length} characters):`,
    fence(style),
    "**Suno, structure tags for the lyrics field:**",
    fence(structure.join("\n")),
    `**Suno, exclude styles** (${exclude.length} characters):`,
    fence(exclude),
    `**ElevenLabs Music, prompt** (${long.length} characters):`,
    fence(long),
  ];
}

/**
 * The generated part of the document: the shared fragments, the comparison
 * table and every prompt in full, formatted as the repository formats
 * Markdown.
 */
export async function renderThemePromptSectionV1(
  data: ThemePromptsV1,
): Promise<string> {
  const { shared } = data;
  const entries = Object.entries(data.factions);
  const parts: string[] = [
    "### Shared fragments",
    `Schema version ${data.schemaVersion}; shared fragments version ${shared.version}. Budgets: Suno style ${shared.budgets.sunoStyleChars} characters, Suno exclude ${shared.budgets.sunoExcludeChars} characters, long prompt ${shared.budgets.longPromptChars} characters. Length: ${shared.length.targetSeconds} seconds, accept ${shared.length.minSeconds}–${shared.length.maxSeconds}. The shared opening: a ${shared.motif}.`,
    "Appended to every faction's Suno style tags:",
    fence(shared.sunoCommonStyle),
    "Put before every faction's Suno exclude tags:",
    fence(shared.sunoCommonExclude),
    "Appended to every faction's long prompt:",
    fence(`${shared.instrumentalSentence} ${shared.longPromptTail}`),
    "### Comparison table",
    table(
      ["Faction", "Tempo", "Metre", "Lead", "Rhythm", "Mood", "Suggested loop"],
      entries.map(([, entry]) => {
        const loop = suggestedLoopV1(
          entry.tempo,
          entry.metre,
          shared.length.targetSeconds,
        );
        return [
          entry.name,
          `${entry.tempo.target} BPM`,
          `${entry.metre.signature}, ${entry.metre.feel}`,
          entry.palette.lead.join(", "),
          entry.palette.rhythm.join(", "),
          entry.mood.join(", "),
          `${loop.bars} bars, ${loop.seconds} s`,
        ];
      }),
    ),
  ];
  for (const [key, entry] of entries) {
    const style = sunoStyleV1(shared, entry);
    const exclude = sunoExcludeV1(shared, entry);
    const long = longPromptV1(shared, entry);
    parts.push(
      `### ${entry.name} (\`${key}\`)`,
      entry.identity,
      table(
        ["Field", "Value"],
        [
          [
            "Prompt version",
            `\`${promptVersionIdV1(shared, key, entry.promptVersion)}\``,
          ],
          ["Theme id", `\`${entry.themeId}\``],
          ["Output file", `\`${entry.outputFile}\``],
          ["Tempo", tempoText(entry.tempo)],
          ["Metre", `${entry.metre.signature}, ${entry.metre.feel}`],
          ["Mode", entry.mode],
          ["Lead", entry.palette.lead.join(", ")],
          ["Rhythm section", entry.palette.rhythm.join(", ")],
          ["Colour", entry.palette.colour.join(", ")],
          ["Mood", entry.mood.join(", ")],
          ["Duration", `${shared.length.targetSeconds} seconds`],
        ],
      ),
      ...promptBlocks(style, entry.sunoStructure, exclude, long),
    );
  }
  parts.push(
    "### Extras: title theme and stingers",
    "These are proposals, not part of the faction set: see [Optional extras](#optional-extras-a-proposal). Their strings are complete as stored; the shared fragments are not added.",
  );
  for (const extra of data.extras) {
    parts.push(
      `#### ${extra.name} (\`${extra.id}\`)`,
      extra.use,
      table(
        ["Field", "Value"],
        [
          [
            "Prompt version",
            `\`${promptVersionIdV1(shared, extra.id, extra.promptVersion)}\``,
          ],
          ["Output file", `\`${extra.outputFile}\``],
          ["Tempo", tempoText(extra.tempo)],
          ["Metre", `${extra.metre.signature}, ${extra.metre.feel}`],
          ["Loops", extra.loop ? "yes" : "no"],
          ["Duration", `${extra.durationSeconds} seconds`],
        ],
      ),
      ...promptBlocks(
        extra.sunoStyle,
        extra.sunoStructure,
        extra.sunoExclude,
        extra.longPrompt,
      ),
    );
  }
  const formatted = await format(parts.join("\n\n"), { parser: "markdown" });
  return formatted.trimEnd();
}

/** The text between the document's markers, or null when they are missing. */
export function generatedSectionV1(doc: string): string | null {
  const begin = doc.indexOf(THEME_SECTION_BEGIN);
  const end = doc.indexOf(THEME_SECTION_END);
  if (begin < 0 || end < begin) return null;
  return doc.slice(begin + THEME_SECTION_BEGIN.length, end).trim();
}

/** The document with `section` between its markers. */
export function withGeneratedSectionV1(doc: string, section: string): string {
  const begin = doc.indexOf(THEME_SECTION_BEGIN);
  const end = doc.indexOf(THEME_SECTION_END);
  if (begin < 0 || end < begin) {
    throw new Error("The document has no theme-prompts markers.");
  }
  return `${doc.slice(0, begin + THEME_SECTION_BEGIN.length)}\n\n${section}\n\n${doc.slice(end)}`;
}

async function main(command: string | undefined): Promise<number> {
  if (command !== "render" && command !== "check") {
    process.stderr.write("Usage: theme-prompts.ts <render|check>\n");
    return 2;
  }
  const data = await loadThemePromptsV1();
  const problems = validateThemePromptsV1(data);
  if (problems.length > 0) {
    process.stderr.write(`${problems.join("\n")}\n`);
    return 1;
  }
  const section = await renderThemePromptSectionV1(data);
  const doc = await readFile(THEME_MUSIC_DOC_PATH, "utf8");
  if (command === "render") {
    const next = withGeneratedSectionV1(doc, section);
    if (next !== doc) await writeFile(THEME_MUSIC_DOC_PATH, next);
    process.stdout.write(
      next === doc
        ? "docs/audio/THEME_MUSIC.md is up to date.\n"
        : "docs/audio/THEME_MUSIC.md rewritten.\n",
    );
    return 0;
  }
  if (generatedSectionV1(doc) !== section) {
    process.stderr.write(
      "docs/audio/THEME_MUSIC.md is out of date: run `npm run audio:theme-prompts -- render`.\n",
    );
    return 1;
  }
  process.stdout.write(
    `Theme prompts are sound: ${Object.keys(data.factions).length} factions, ${data.extras.length} extras.\n`,
  );
  return 0;
}

if (
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  process.exitCode = await main(process.argv[2]);
}
