import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import {
  THEME_MUSIC_OUTPUT_V1,
  THEME_MUSIC_TRACKS_V1,
  type ThemeMusicTrackV1,
} from "../../src/audio/theme-music";

/**
 * The records of the theme music (bead pulp_wars-2yc.27,
 * docs/audio/THEME_MUSIC.md "Records"): one record per encoded theme,
 * written from `src/audio/theme-music.json`, so that the numbers in the
 * document are the ones the game plays with.
 *
 *   npx tsx scripts/audio/theme-records.ts render   rewrites the Records section
 *   npx tsx scripts/audio/theme-records.ts check    fails when it is out of date
 *
 * What only the person who generated the music knows (the model, the plan
 * and its terms, the takes) is left marked for them to fill in; the text
 * of those cells is kept when the section is written again.
 */

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
export const THEME_RECORDS_DOC_PATH = resolve(
  ROOT,
  "docs/audio/THEME_MUSIC.md",
);
export const THEME_RECORDS_BEGIN =
  "<!-- theme-records:begin (generated by scripts/audio/theme-records.ts from src/audio/theme-music.json; the cells marked for the author are kept) -->";
export const THEME_RECORDS_END = "<!-- theme-records:end -->";

/** The day the user generated the nine masters, and with what. */
export const THEME_RECORDS_DATE_V1 = "2026-10-07";
export const THEME_RECORDS_SERVICE_V1 = "Suno";
/** The commit of `theme-prompts.json` the prompts were read from. */
export const THEME_RECORDS_PROMPTS_COMMIT_V1 = "5dae5a51";
/** What a cell says until its author fills it in. */
export const THEME_RECORDS_AUTHOR_V1 = "To be filled by the author";
/** The fields only the author can fill in. */
export const THEME_RECORDS_AUTHOR_FIELDS_V1 = [
  "Model or version",
  "Fields used",
  "Changes to the prompt",
  "Takes generated",
  "Plan and licence",
] as const;

const decibels = (gain: number): string => {
  const value = 20 * Math.log10(gain);
  return `${value >= 0 ? "+" : "−"}${Math.abs(value).toFixed(2)} dB`;
};

const minus = (value: number, digits = 2): string =>
  value.toFixed(digits).replace("-", "−");

/** The fields of one record, in the template's order. */
export function themeRecordFieldsV1(
  track: ThemeMusicTrackV1,
  kept: Readonly<Record<string, string>> = {},
): readonly (readonly [string, string])[] {
  const author = (field: string, hint = ""): string =>
    kept[field] ?? `${THEME_RECORDS_AUTHOR_V1}${hint}`;
  const trims = [
    track.headTrimSeconds > 0
      ? `${track.headTrimSeconds} s cut from the start`
      : "nothing cut from the start",
    track.tailTrimSeconds > 0
      ? `${track.tailTrimSeconds} s of silence cut from the end`
      : "nothing cut from the end",
  ].join(", ");
  const played = track.lufs + 20 * Math.log10(track.gain);
  return [
    ["Theme id", `\`${track.id}\``],
    ["Output file", `\`${THEME_MUSIC_OUTPUT_V1.folder}/${track.file}\``],
    ["Date", THEME_RECORDS_DATE_V1],
    ["Service", THEME_RECORDS_SERVICE_V1],
    ["Model or version", author("Model or version")],
    [
      "Prompt version",
      `\`${track.prompt}\`, \`theme-prompts.json\` at commit \`${THEME_RECORDS_PROMPTS_COMMIT_V1}\``,
    ],
    ["Fields used", author("Fields used")],
    ["Changes to the prompt", author("Changes to the prompt")],
    ["Takes generated", author("Takes generated")],
    [
      "Take chosen",
      `The author's file \`${track.master}\`: the author's own choice among the takes`,
    ],
    [
      "Edits",
      `None in the service that is known. By \`scripts/audio/encode-themes.ts\`: ${trims}; no fade, no level change and no loop edit in the file; encoded ${THEME_MUSIC_OUTPUT_V1.codec} stereo ${THEME_MUSIC_OUTPUT_V1.sampleRate / 1000} kHz at ${THEME_MUSIC_OUTPUT_V1.bitRate / 1000} kbit/s (${track.bytes.toLocaleString("en-US")} bytes). In the game: played at gain ${track.gain} (${decibels(track.gain)}). Loop: the master ends on a note that dies away (${minus(track.endLevelDb, 1)} dBFS in its last 50 ms), so the next pass starts ${track.loopOverlapSeconds} s before the end and the ending pass is faded out under it, in the player`,
    ],
    [
      "Final loudness",
      `${minus(track.lufs)} LUFS integrated and a sample peak of ${minus(track.peakDb)} dBFS in the file; ${minus(played, 1)} LUFS as played, before the mixer's music level. True peak not measured`,
    ],
    [
      "Length",
      `${track.seconds} s (the master: ${track.masterSeconds} s). Bars not counted`,
    ],
    [
      "Plan and licence",
      author(
        "Plan and licence",
        ": the plan the account was on that day, and what its terms said about commercial use and ownership",
      ),
    ],
    [
      "Checklist",
      "Not recorded by the author. The loop join was set by measurement and has not been listened to",
    ],
    [
      "Raw take kept at",
      `The author's \`suno_score\` folder, outside the repository, as \`${track.master}\``,
    ],
  ];
}

/** The author's own cells of a record already in the document. */
function keptCells(doc: string, id: string): Record<string, string> {
  const kept: Record<string, string> = {};
  const from = doc.indexOf(`### ${id}, `);
  if (from < 0) return kept;
  const next = doc.indexOf("\n### ", from + 1);
  const end = doc.indexOf(THEME_RECORDS_END, from);
  const block = doc.slice(from, next < 0 || next > end ? end : next);
  for (const field of THEME_RECORDS_AUTHOR_FIELDS_V1) {
    const row = block
      .split("\n")
      .find((line) => line.startsWith(`| ${field} `));
    const value = row?.split("|")[2]?.trim();
    if (value !== undefined && value !== "") kept[field] = value;
  }
  return kept;
}

/** The Records section, formatted as the document is. */
export async function renderThemeRecordsV1(
  doc = "",
  tracks: readonly ThemeMusicTrackV1[] = THEME_MUSIC_TRACKS_V1,
): Promise<string> {
  const total = tracks.reduce((sum, track) => sum + track.bytes, 0);
  const parts = [
    `${tracks.length} themes, ${THEME_RECORDS_SERVICE_V1}, ${THEME_RECORDS_DATE_V1}; ${(total / 1e6).toFixed(1)} MB together. The masters were measured and encoded by \`scripts/audio/encode-themes.ts\`; every number below is from \`src/audio/theme-music.json\`, which that script writes.`,
    `**Still to be filled in by the author**, in every record: the model or version exactly as Suno showed it, which blocks went into which fields, any change to the prompt, the number of takes, and the plan with its terms. The plan's terms on the day a track was generated decide whether it may be used commercially; until that cell is filled in, that is not established.`,
    [
      "| Theme | Master | Length | Cut from start / end | Loudness | Peak | Gain | Ends at | Loop overlap | Size |",
      "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
      ...tracks.map(
        (track) =>
          `| \`${track.id}\` | \`${track.master}\` | ${track.seconds} s | ${track.headTrimSeconds} s / ${track.tailTrimSeconds} s | ${minus(track.lufs)} LUFS | ${minus(track.peakDb)} dBFS | ${track.gain} | ${minus(track.endLevelDb, 1)} dBFS | ${track.loopOverlapSeconds} s | ${(track.bytes / 1e6).toFixed(2)} MB |`,
      ),
    ].join("\n"),
    ...tracks.map((track) =>
      [
        `### ${track.id}, ${THEME_RECORDS_DATE_V1}`,
        "",
        "| Field | Value |",
        "| --- | --- |",
        ...themeRecordFieldsV1(track, keptCells(doc, track.id)).map(
          ([field, value]) => `| ${field} | ${value} |`,
        ),
      ].join("\n"),
    ),
  ];
  const formatted = await format(parts.join("\n\n"), { parser: "markdown" });
  return formatted.trimEnd();
}

/** The text between the document's markers, or null when they are missing. */
export function themeRecordsSectionV1(doc: string): string | null {
  const begin = doc.indexOf(THEME_RECORDS_BEGIN);
  const end = doc.indexOf(THEME_RECORDS_END);
  if (begin < 0 || end < begin) return null;
  return doc.slice(begin + THEME_RECORDS_BEGIN.length, end).trim();
}

async function main(command: string | undefined): Promise<number> {
  if (command !== "render" && command !== "check") {
    process.stderr.write("Usage: theme-records.ts <render|check>\n");
    return 2;
  }
  const doc = await readFile(THEME_RECORDS_DOC_PATH, "utf8");
  const begin = doc.indexOf(THEME_RECORDS_BEGIN);
  const end = doc.indexOf(THEME_RECORDS_END);
  if (begin < 0 || end < begin) {
    process.stderr.write("The document has no theme-records markers.\n");
    return 1;
  }
  const section = await renderThemeRecordsV1(doc);
  if (command === "render") {
    const next = `${doc.slice(0, begin + THEME_RECORDS_BEGIN.length)}\n\n${section}\n\n${doc.slice(end)}`;
    if (next !== doc) await writeFile(THEME_RECORDS_DOC_PATH, next);
    process.stdout.write(
      next === doc
        ? "The records are up to date.\n"
        : "docs/audio/THEME_MUSIC.md: records rewritten.\n",
    );
    return 0;
  }
  if (themeRecordsSectionV1(doc) !== section) {
    process.stderr.write(
      "The records are out of date: run `npx tsx scripts/audio/theme-records.ts render`.\n",
    );
    return 1;
  }
  process.stdout.write(
    `The records are those of ${THEME_MUSIC_TRACKS_V1.length} themes.\n`,
  );
  return 0;
}

if (
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  process.exitCode = await main(process.argv[2]);
}
