// @vitest-environment jsdom

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { bootstrapRuleset7App } from "../../src/app/index";
import {
  AUDIO_SETTINGS_STORAGE_KEY_V1,
  SOUND_IDS_V1,
  SOUND_MANIFEST_V1,
  SOUND_THEMES_V1,
  SOUND_TITLE_THEME_ID_V1,
  STOCK_SOUNDS_V1,
  STOCK_SOUND_CLIPS_V1,
  STOCK_SOUND_PICKS_STORAGE_KEY_V1,
  clearSoundFilesV1,
  soundRecipeV1,
  stockSoundCandidateV1,
  stockSoundPickSummaryV1,
  stockSoundUrlV1,
  stockSoundV1,
  synthRecipeDurationMsV1,
  type SoundIdV1,
} from "../../src/audio/index";
import {
  installFakeAudioContext,
  uninstallFakeAudioContext,
  type FakeAudioDeviceV1,
} from "../fixtures/fake-audio-context";
import { RecordingBoardHost } from "../fixtures/v7-dom-rig";

/**
 * Choosing between recordings in the Gallery's Sounds tab (bead
 * pulp_wars-2yc.24, docs/ui/SOUND.md "Choosing between recordings"): a
 * sound with recordings lists them under its card as a numbered row; a
 * line plays its recording (fetched when asked for) and its Use control
 * picks it for this browser, which the game then plays and remembers;
 * "Copy my picks" hands the picks over as text. jsdom has no WebAudio and
 * no files: a recording device and a `fetch` stand in.
 */

/** Default is its first recording; two alternatives. */
const HIT: SoundIdV1 = "impact.hit";
/** Generated by default; one recording to compare. */
const DEATH: SoundIdV1 = "unit.death";
/** No recording at all. */
const ARROW: SoundIdV1 = "attack.ranged";

/** The menus' theme: the one piece of music the first gesture asks for. */
const TITLE_THEME_URL = ((): string => {
  const source = SOUND_THEMES_V1.find(
    (theme) => theme.id === SOUND_TITLE_THEME_ID_V1,
  )?.source;
  if (source?.kind !== "FILE") throw new Error("no title theme file");
  return source.url;
})();

/** In the stand-in device, candidate n of any sound decodes to this long. */
const seconds = (n: number): number => 0.5 + n / 10;

let app: ReturnType<typeof bootstrapRuleset7App> | null = null;
let device: FakeAudioDeviceV1;
let fetched: string[] = [];
let missing = new Set<string>();

function mount(): ReturnType<typeof bootstrapRuleset7App> {
  app = bootstrapRuleset7App(document, {
    storage: null,
    settingsStorage: window.localStorage,
    galleryDemoHost: () => new RecordingBoardHost(),
  });
  return app;
}

function required<T extends Element = HTMLElement>(selector: string): T {
  const node = document.querySelector<T>(selector);
  if (node === null) throw new Error(`Missing ${selector}`);
  return node;
}

function button(action: string): HTMLButtonElement {
  return required<HTMLButtonElement>(`[data-action="${action}"]`);
}

function openSounds(): HTMLElement {
  button("gallery").click();
  button("gallery-tab-sounds").click();
  return required("[data-v7-gallery-sounds]");
}

function row(id: string): HTMLElement {
  return required(`[data-sound-row="${id}"]`);
}

function card(id: string): HTMLButtonElement {
  return required<HTMLButtonElement>(`[data-sound-play="${id}"]`);
}

function choices(id: string): HTMLElement[] {
  return [...row(id).querySelectorAll<HTMLElement>(".v7-gallery-sound-choice")];
}

function choicePlay(id: string, n: number): HTMLButtonElement {
  return required<HTMLButtonElement>(
    `[data-sound-row="${id}"] .v7-gallery-sound-choice-play[data-choice="${n}"]`,
  );
}

function choiceUse(id: string, n: number): HTMLButtonElement {
  return required<HTMLButtonElement>(
    `[data-sound-row="${id}"] .v7-gallery-sound-choice-use[data-choice="${n}"]`,
  );
}

function chosen(id: string): string[] {
  return choices(id)
    .filter((node) => node.dataset.chosen === "true")
    .map((node) => node.dataset.choice ?? "");
}

function url(id: string, n: number): string {
  const clip = stockSoundCandidateV1(id, n);
  if (clip === null) throw new Error(`${id} #${n}`);
  return stockSoundUrlV1(clip);
}

function synthSeconds(id: SoundIdV1): number {
  const recipe = soundRecipeV1(id);
  if (recipe === null) throw new Error(`${id} has no recipe`);
  return Math.ceil((synthRecipeDurationMsV1(recipe) / 1000) * 44100) / 44100;
}

function storedPicks(): unknown {
  const value = window.localStorage.getItem(STOCK_SOUND_PICKS_STORAGE_KEY_V1);
  return value === null ? null : JSON.parse(value);
}

function key(target: Element, value: string): KeyboardEvent {
  const event = new KeyboardEvent("keydown", {
    key: value,
    bubbles: true,
    cancelable: true,
  });
  target.dispatchEvent(event);
  return event;
}

/** Lets a fetch, a decode and the play after them settle. */
async function settle(): Promise<void> {
  for (let turn = 0; turn < 40; turn += 1) await Promise.resolve();
}

beforeEach(() => {
  document.body.innerHTML = '<div id="app"></div>';
  window.localStorage.clear();
  clearSoundFilesV1();
  fetched = [];
  missing = new Set();
  // The bytes name the file, so the device can tell the recordings apart.
  Object.defineProperty(window, "fetch", {
    configurable: true,
    writable: true,
    value: (address: string): Promise<unknown> => {
      fetched.push(address);
      const ok = !missing.has(address);
      return Promise.resolve({
        ok,
        status: ok ? 200 : 404,
        arrayBuffer: () =>
          Promise.resolve(new TextEncoder().encode(`CLIP ${address}`).buffer),
      });
    },
  });
  device = installFakeAudioContext(window, {
    decode(data) {
      const n = /-(\d+)\.m4a$/.exec(new TextDecoder().decode(data))?.[1];
      if (n === undefined) throw new Error("Unable to decode audio data");
      return seconds(Number(n));
    },
  });
});

afterEach(() => {
  app?.destroy();
  app = null;
  vi.useRealTimers();
  uninstallFakeAudioContext(window);
  Reflect.deleteProperty(window, "fetch");
  Reflect.deleteProperty(window.navigator, "clipboard");
  clearSoundFilesV1();
});

describe("Gallery Sounds tab: the recordings of a sound", () => {
  it("lists them under the card as a numbered row, the generated sound last", () => {
    mount();
    openSounds();
    expect(STOCK_SOUNDS_V1.length).toBeGreaterThan(0);
    for (const sound of STOCK_SOUNDS_V1) {
      const items = choices(sound.id);
      expect(row(sound.id).dataset.choices, sound.id).toBe("true");
      expect(items.map((node) => node.dataset.choice)).toEqual([
        ...sound.candidates.map((candidate) => String(candidate.n)),
        "0",
      ]);
      // Exactly one is the default, and without a pick it is the one in use.
      expect(
        items
          .filter((node) => node.dataset.default === "true")
          .map((node) => node.dataset.choice),
        sound.id,
      ).toEqual([String(sound.default)]);
      expect(chosen(sound.id), sound.id).toEqual([String(sound.default)]);
      const label = SOUND_MANIFEST_V1[sound.id as SoundIdV1].label;
      expect(
        row(sound.id)
          .querySelector(".v7-gallery-sound-choices")
          ?.getAttribute("aria-label"),
      ).toBe(`Recordings of ${label}`);
      for (const candidate of sound.candidates) {
        const play = choicePlay(sound.id, candidate.n);
        const isDefault = candidate.n === sound.default;
        const origin = `${candidate.library} / ${candidate.originalFile}`;
        const cut = `${candidate.startSeconds}–${candidate.endSeconds} s`;
        // The number, the file it was cut from and the stretch are shown;
        // the whole origin and the note are in the name and the title.
        expect(
          play.querySelector(".v7-gallery-sound-choice-number")?.textContent,
        ).toBe(String(candidate.n));
        expect(
          play.querySelector(".v7-gallery-sound-choice-file")?.textContent,
        ).toBe(candidate.originalFile);
        expect(
          play.querySelector(".v7-gallery-sound-choice-cut")?.textContent,
        ).toBe(cut);
        expect(
          play.querySelector(".v7-gallery-sound-choice-default")?.textContent,
          `${sound.id} #${candidate.n}`,
        ).toBe(isDefault ? "default" : undefined);
        expect(play.getAttribute("aria-label")).toBe(
          `Play recording ${candidate.n} of ${label}${isDefault ? " (default)" : ""}: ${origin}, ${cut}. ${candidate.note}`,
        );
        expect(play.title).toBe(play.getAttribute("aria-label"));
        const use = choiceUse(sound.id, candidate.n);
        expect(use.getAttribute("aria-label")).toBe(
          `Use recording ${candidate.n} for ${label}`,
        );
        expect(use.getAttribute("aria-pressed")).toBe(String(isDefault));
        expect(use.textContent).toBe(isDefault ? "In use" : "Use");
        expect(play.type).toBe("button");
        expect(use.type).toBe("button");
      }
      // The generated sound closes the row.
      const generated = choicePlay(sound.id, 0);
      expect(
        generated.querySelector(".v7-gallery-sound-choice-file")?.textContent,
      ).toBe("Generated");
      expect(generated.getAttribute("aria-label")).toBe(
        `Play generated: ${label}${sound.default === 0 ? " (default)" : ""}`,
      );
      expect(choiceUse(sound.id, 0).getAttribute("aria-label")).toBe(
        `Use the generated sound for ${label}`,
      );
    }
    // A sound without recordings has no row; neither has a theme.
    const withChoices = new Set(STOCK_SOUNDS_V1.map((sound) => sound.id));
    for (const id of SOUND_IDS_V1) {
      if (withChoices.has(id)) continue;
      expect(row(id).dataset.choices, id).toBeUndefined();
      expect(row(id).querySelector(".v7-gallery-sound-choices"), id).toBeNull();
    }
    expect(document.querySelectorAll(".v7-gallery-sound-choices").length).toBe(
      STOCK_SOUNDS_V1.length,
    );
    expect(row(ARROW).querySelector(".v7-gallery-sound-choice")).toBeNull();
    // No manifest id is shown as text, here either.
    for (const id of SOUND_IDS_V1)
      expect(row(id).textContent ?? "", id).not.toContain(id);
  });

  it("marks the generated sound as the default of a sound that is generated", () => {
    mount();
    openSounds();
    expect(stockSoundV1(DEATH)?.default).toBe(0);
    expect(row(DEATH).dataset.origin).toBe("generated");
    expect(chosen(DEATH)).toEqual(["0"]);
    expect(
      choicePlay(DEATH, 0).querySelector(".v7-gallery-sound-choice-default")
        ?.textContent,
    ).toBe("default");
    expect(choiceUse(DEATH, 0).getAttribute("aria-pressed")).toBe("true");
    expect(choiceUse(DEATH, 1).getAttribute("aria-pressed")).toBe("false");
    // Its card is still a generated card: no "Generated" variant beside it.
    expect(row(DEATH).querySelector('[data-variant="generated"]')).toBeNull();
  });

  it("fetches an alternative when it is played, not before, and plays it", async () => {
    const view = mount().view;
    openSounds();
    // Opening the Gallery was the first gesture: the defaults were asked
    // for, and the menus' title theme (the one theme, bead 2yc.27).
    await settle();
    expect([...fetched].sort()).toEqual(
      [
        ...STOCK_SOUND_CLIPS_V1.map((clip) => stockSoundUrlV1(clip)),
        TITLE_THEME_URL,
      ].sort(),
    );
    expect(fetched).not.toContain(url(HIT, 2));
    const play = vi.spyOn(view.audio, "play");
    const before = device.sources.length;
    // The Gallery and tab buttons clicked on the way here.
    view.audio.clearLog();

    choicePlay(HIT, 2).click();
    expect(row(HIT).dataset.loadingChoice).toBe("2");
    await settle();
    expect(fetched.filter((entry) => entry === url(HIT, 2))).toHaveLength(1);
    expect(row(HIT).dataset.loadingChoice).toBeUndefined();
    expect(play).toHaveBeenLastCalledWith(HIT, { candidate: 2 });
    expect(device.sources.length).toBe(before + 1);
    expect(device.sources.at(-1)?.seconds).toBe(seconds(2));
    // The card is marked as playing, and so is that line.
    expect(row(HIT).dataset.playing).toBe("true");
    expect(row(HIT).dataset.playingChoice).toBe("2");
    // Hearing it did not pick it.
    expect(chosen(HIT)).toEqual(["1"]);
    expect(storedPicks()).toBeNull();
    expect(view.audio.soundCandidate(HIT)).toBe(1);

    // Played again, it is not fetched again.
    choicePlay(HIT, 2).click();
    await settle();
    expect(fetched.filter((entry) => entry === url(HIT, 2))).toHaveLength(1);
    expect(device.sources.at(-1)?.seconds).toBe(seconds(2));

    // The default's own line plays the default; the last line the synth.
    choicePlay(HIT, 1).click();
    await settle();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(1));
    expect(row(HIT).dataset.playingChoice).toBe("1");
    choicePlay(HIT, 0).click();
    expect(play).toHaveBeenLastCalledWith(HIT, { generated: true });
    expect(device.sources.at(-1)?.seconds).toBeCloseTo(synthSeconds(HIT), 6);
    expect(row(HIT).dataset.playingChoice).toBeUndefined();
    // No interface click was added to any of it.
    expect(view.audio.log.some((entry) => entry.id === "ui.click")).toBe(false);
  });

  it("says so when a recording cannot be loaded", async () => {
    missing.add(url(HIT, 3));
    mount();
    openSounds();
    await settle();
    const before = device.sources.length;
    const notice = required(".v7-gallery-sounds-notice");
    expect(notice.hidden).toBe(true);
    choicePlay(HIT, 3).click();
    await settle();
    expect(device.sources.length).toBe(before);
    expect(row(HIT).dataset.playing).toBe("false");
    expect(notice.hidden).toBe(false);
    expect(notice.dataset.reason).toBe("file");
    expect(notice.textContent).toBe("That recording could not be loaded");
    // Another line still plays, and takes the notice away.
    choicePlay(HIT, 2).click();
    await settle();
    expect(device.sources.length).toBe(before + 1);
    expect(notice.hidden).toBe(true);
  });

  it("says there is no sound device when a line is played without one", async () => {
    uninstallFakeAudioContext(window);
    mount();
    openSounds();
    const notice = required(".v7-gallery-sounds-notice");
    choicePlay(HIT, 2).click();
    await settle();
    expect(fetched).toEqual([]);
    expect(notice.hidden).toBe(false);
    expect(notice.dataset.reason).toBe("device");
    expect(notice.textContent).toBe("No sound on this device");
    expect(row(HIT).dataset.playing).toBe("false");
    // A pick is still taken and stored: it is a preference, not a sound.
    choiceUse(HIT, 2).click();
    expect(chosen(HIT)).toEqual(["2"]);
    expect(storedPicks()).toEqual({ [HIT]: 2 });
  });

  it("points at the notice instead of playing with sound off", async () => {
    window.localStorage.setItem(
      AUDIO_SETTINGS_STORAGE_KEY_V1,
      '{"enabled":false,"volume":70}',
    );
    mount();
    openSounds();
    choicePlay(HIT, 2).click();
    await settle();
    expect(fetched).toEqual([]);
    expect(device.contexts()).toBe(0);
    expect(required(".v7-gallery-sounds-notice").dataset.nudged).toBe("true");
  });
});

describe("Gallery Sounds tab: picking a recording", () => {
  it("makes the game play the picked recording at once, and remembers it", async () => {
    const view = mount().view;
    openSounds();
    await settle();
    const use = choiceUse(HIT, 2);
    use.focus();
    use.click();
    await settle();

    expect(view.audio.picks).toEqual({ [HIT]: 2 });
    expect(storedPicks()).toEqual({ [HIT]: 2 });
    expect(fetched).toContain(url(HIT, 2));
    expect(view.audio.soundCandidate(HIT)).toBe(2);
    // The row marks it; the default keeps its own mark.
    expect(chosen(HIT)).toEqual(["2"]);
    expect(choiceUse(HIT, 2).getAttribute("aria-pressed")).toBe("true");
    expect(choiceUse(HIT, 2).textContent).toBe("In use");
    expect(choiceUse(HIT, 1).getAttribute("aria-pressed")).toBe("false");
    expect(choiceUse(HIT, 1).textContent).toBe("Use");
    expect(
      choicePlay(HIT, 1).querySelector(".v7-gallery-sound-choice-default"),
    ).not.toBeNull();
    // The card was drawn again; the focus is on the same control.
    expect(document.activeElement).toBe(choiceUse(HIT, 2));
    // The card says what the sound plays now.
    const picked = stockSoundCandidateV1(HIT, 2);
    if (picked === null) throw new Error("missing candidate");
    expect(
      row(HIT).querySelector(".v7-gallery-sound-origin-file")?.textContent,
    ).toBe(picked.originalFile);
    expect(card(HIT).getAttribute("aria-label")).toBe(
      `Play: Hit. Recorded: ${picked.library} / ${picked.originalFile}, ${picked.startSeconds}–${picked.endSeconds} s`,
    );
    // The card plays the sound as a match does: the picked recording.
    card(HIT).click();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(2));
    // What the game itself asks for is the picked recording too.
    view.audio.stop(HIT);
    expect(view.audio.play(HIT)).toBe("PLAYED");
    expect(device.sources.at(-1)?.seconds).toBe(seconds(2));
    // The other cards are as they were.
    expect(chosen("impact.heavy")).toEqual(["1"]);
    expect(required("[data-sound-pick-count]").textContent).toBe("1 pick.");

    // Picking the default again forgets the pick.
    choiceUse(HIT, 1).click();
    await settle();
    expect(view.audio.picks).toEqual({});
    expect(storedPicks()).toBeNull();
    expect(chosen(HIT)).toEqual(["1"]);
    expect(required("[data-sound-pick-count]").textContent).toBe(
      "No picks yet.",
    );
    card(HIT).click();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(1));
  });

  it("can set a recorded sound back to its generated version", async () => {
    const view = mount().view;
    openSounds();
    await settle();
    expect(row(HIT).dataset.origin).toBe("recorded");
    choiceUse(HIT, 0).click();
    expect(view.audio.picks).toEqual({ [HIT]: 0 });
    expect(chosen(HIT)).toEqual(["0"]);
    expect(row(HIT).dataset.origin).toBe("generated");
    expect(
      row(HIT).querySelector(".v7-gallery-sound-origin")?.textContent,
    ).toBe("Generated");
    expect(card(HIT).getAttribute("aria-label")).toBe("Play: Hit. Generated");
    // The card is generated now: no "Generated" variant beside the pitches.
    expect(row(HIT).querySelector('[data-variant="generated"]')).toBeNull();
    card(HIT).click();
    expect(device.sources.at(-1)?.seconds).toBeCloseTo(synthSeconds(HIT), 6);
    expect(view.audio.soundSource(HIT)).toBe("GENERATED");
  });

  it("can give a sound that is generated by default its recording", async () => {
    const view = mount().view;
    openSounds();
    await settle();
    expect(fetched).not.toContain(url(DEATH, 1));
    choiceUse(DEATH, 1).click();
    await settle();
    expect(fetched).toContain(url(DEATH, 1));
    expect(view.audio.picks).toEqual({ [DEATH]: 1 });
    expect(chosen(DEATH)).toEqual(["1"]);
    expect(row(DEATH).dataset.origin).toBe("recorded");
    // A recorded card: its generated version is beside the pitches again.
    expect(
      row(DEATH).querySelector('[data-variant="generated"]'),
    ).not.toBeNull();
    card(DEATH).click();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(1));
    // The generated sound is still marked as the default.
    expect(
      choicePlay(DEATH, 0).querySelector(".v7-gallery-sound-choice-default"),
    ).not.toBeNull();
  });

  it("applies the stored picks after a reload", async () => {
    mount();
    openSounds();
    await settle();
    choiceUse(HIT, 3).click();
    choiceUse(DEATH, 1).click();
    await settle();
    app?.destroy();
    app = null;
    clearSoundFilesV1();
    fetched = [];
    document.body.innerHTML = '<div id="app"></div>';

    const view = mount().view;
    expect(view.audio.picks).toEqual({ [HIT]: 3, [DEATH]: 1 });
    // The Gallery opens on the remembered Sounds tab.
    button("gallery").click();
    await settle();
    // The picked recordings were fetched, not the default they replace.
    expect(fetched).toContain(url(HIT, 3));
    expect(fetched).not.toContain(url(HIT, 1));
    expect(fetched).toContain(url(DEATH, 1));
    expect(chosen(HIT)).toEqual(["3"]);
    expect(chosen(DEATH)).toEqual(["1"]);
    expect(required("[data-sound-pick-count]").textContent).toBe("2 picks.");
    card(HIT).click();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(3));
  });

  it("ignores a stored pick whose recording no longer exists", async () => {
    window.localStorage.setItem(
      STOCK_SOUND_PICKS_STORAGE_KEY_V1,
      JSON.stringify({ [HIT]: 99, [ARROW]: 1, nonsense: 2 }),
    );
    const view = mount().view;
    openSounds();
    await settle();
    expect(view.audio.picks).toEqual({});
    expect(chosen(HIT)).toEqual(["1"]);
    expect(fetched).toContain(url(HIT, 1));
    expect(required("[data-sound-pick-count]").textContent).toBe(
      "No picks yet.",
    );
    card(HIT).click();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(1));
  });

  it("reaches every line with the arrow keys, card by card with Tab", () => {
    mount();
    const panel = openSounds();
    const hit = card(HIT);
    // Tab walks the cards; the lines under a card are reached with the arrows.
    expect(hit.tabIndex).toBe(0);
    for (const node of panel.querySelectorAll<HTMLElement>(
      ".v7-gallery-sound-choice-play, .v7-gallery-sound-choice-use",
    )) {
      expect(node.tabIndex).toBe(-1);
      expect(node.dataset.soundControl).toBe("true");
    }
    const order = [
      ...row(HIT).querySelectorAll<HTMLElement>("[data-sound-control]"),
    ].filter((node) => !node.hidden);
    // The card, its pitches and generated version, then the lines in order.
    expect(order.map((node) => node.getAttribute("aria-label"))).toEqual([
      hit.getAttribute("aria-label"),
      "Play lower: Hit",
      "Play higher: Hit",
      "Play generated: Hit",
      ...[1, 2, 3].flatMap((n) => [
        choicePlay(HIT, n).getAttribute("aria-label"),
        `Use recording ${n} for Hit`,
      ]),
      "Play generated: Hit",
      "Use the generated sound for Hit",
    ]);
    hit.focus();
    for (const next of order.slice(1)) {
      const from = document.activeElement as HTMLElement;
      expect(key(from, "ArrowRight").defaultPrevented).toBe(true);
      expect(document.activeElement).toBe(next);
    }
    // Right from the last line is the next card; Left comes back.
    const last = document.activeElement as HTMLElement;
    key(last, "ArrowRight");
    expect(document.activeElement).toBe(card("impact.heavy"));
    key(card("impact.heavy"), "ArrowLeft");
    expect(document.activeElement).toBe(last);
    // Up and Down from a line go to the cards above and below.
    key(last, "ArrowDown");
    expect(document.activeElement).toBe(card("impact.heavy"));
    // Enter and Space press a line as they press any button.
    expect(choiceUse(HIT, 2).tagName).toBe("BUTTON");
  });
});

describe("Gallery Sounds tab: the picks as text", () => {
  it("says how many sounds have recordings and how many have a pick", () => {
    mount();
    openSounds();
    const bar = required("[data-v7-sound-picks]");
    expect(bar.hidden).toBe(false);
    expect(required(".v7-gallery-sounds-picks-text").textContent).toBe(
      `No picks yet. ${STOCK_SOUNDS_V1.length} sounds have recordings. Play the numbered ones under a card and press Use on the one you like: the game plays it from then on, in this browser.`,
    );
    // Nothing to forget yet.
    expect(button("gallery-sound-picks-reset").hidden).toBe(true);
    expect(button("gallery-sound-picks-copy").textContent).toBe(
      "Copy my picks",
    );
    expect(
      required<HTMLTextAreaElement>("[data-sound-pick-output]").hidden,
    ).toBe(true);
  });

  it("copies the picks as compact text and shows it", async () => {
    const written: string[] = [];
    Object.defineProperty(window.navigator, "clipboard", {
      configurable: true,
      value: {
        writeText: (text: string): Promise<void> => {
          written.push(text);
          return Promise.resolve();
        },
      },
    });
    const view = mount().view;
    openSounds();
    await settle();
    choiceUse(HIT, 2).click();
    choiceUse(DEATH, 1).click();
    choiceUse("impact.heavy", 0).click();
    await settle();
    const expected = stockSoundPickSummaryV1(view.audio.picks);
    button("gallery-sound-picks-copy").click();
    await settle();
    expect(written).toEqual([expected]);
    expect(JSON.parse(expected)).toMatchObject({
      pulpWarsSoundPicks: 1,
      picks: { [HIT]: 2, "impact.heavy": 0, [DEATH]: 1 },
    });
    const output = required<HTMLTextAreaElement>("[data-sound-pick-output]");
    expect(output.hidden).toBe(false);
    expect(output.readOnly).toBe(true);
    expect(output.value).toBe(expected);
    expect(output.getAttribute("aria-label")).toBe("Your picks, as text");
    const status = required(".v7-gallery-sounds-picks-status");
    expect(status.getAttribute("role")).toBe("status");
    expect(status.textContent).toBe("Copied");
    // The text on show follows a later pick.
    choiceUse(HIT, 3).click();
    await settle();
    expect(output.value).toBe(stockSoundPickSummaryV1(view.audio.picks));
    expect(JSON.parse(output.value)).toMatchObject({ picks: { [HIT]: 3 } });
  });

  it("shows the text selected, to copy by hand, where there is no clipboard", async () => {
    mount();
    openSounds();
    await settle();
    choiceUse(HIT, 2).click();
    await settle();
    button("gallery-sound-picks-copy").click();
    await settle();
    const output = required<HTMLTextAreaElement>("[data-sound-pick-output]");
    expect(output.hidden).toBe(false);
    expect(JSON.parse(output.value)).toMatchObject({ picks: { [HIT]: 2 } });
    expect(required(".v7-gallery-sounds-picks-status").textContent).toBe(
      "Select the text below and copy it",
    );
    expect(document.activeElement).toBe(output);
    expect(output.selectionStart).toBe(0);
    expect(output.selectionEnd).toBe(output.value.length);
  });

  it("forgets every pick from its reset control", async () => {
    const view = mount().view;
    openSounds();
    await settle();
    choiceUse(HIT, 2).click();
    choiceUse(DEATH, 1).click();
    await settle();
    const reset = button("gallery-sound-picks-reset");
    expect(reset.hidden).toBe(false);
    reset.click();
    await settle();
    expect(view.audio.picks).toEqual({});
    expect(storedPicks()).toBeNull();
    expect(chosen(HIT)).toEqual(["1"]);
    expect(chosen(DEATH)).toEqual(["0"]);
    expect(row(DEATH).dataset.origin).toBe("generated");
    expect(reset.hidden).toBe(true);
    expect(required(".v7-gallery-sounds-picks-status").textContent).toBe(
      "Picks cleared",
    );
    expect(document.activeElement).toBe(button("gallery-sound-picks-copy"));
    card(HIT).click();
    expect(device.sources.at(-1)?.seconds).toBe(seconds(1));
  });

  it("offers no choice, and fetches nothing, with ?stock-sounds=0", async () => {
    window.localStorage.setItem(
      STOCK_SOUND_PICKS_STORAGE_KEY_V1,
      JSON.stringify({ [HIT]: 2 }),
    );
    window.history.replaceState(null, "", "?stock-sounds=0");
    try {
      const view = mount().view;
      openSounds();
      await settle();
      expect(view.audio.stockSounds).toBe(false);
      expect(view.audio.picks).toEqual({});
      expect(document.querySelector(".v7-gallery-sound-choices")).toBeNull();
      expect(document.querySelector('[data-choices="true"]')).toBeNull();
      expect(required("[data-v7-sound-picks]").hidden).toBe(true);
      card(HIT).click();
      expect(device.sources.at(-1)?.seconds).toBeCloseTo(synthSeconds(HIT), 6);
      // No clip at all; the title theme is music, not a recording of a
      // sound, and the switch does not concern it.
      expect(fetched).toEqual([TITLE_THEME_URL]);
      // The stored pick is kept for a visit with the recordings on.
      expect(storedPicks()).toEqual({ [HIT]: 2 });
    } finally {
      window.history.replaceState(null, "", window.location.pathname);
    }
  });
});
