import type { FactionIdV7 } from "../engine/v7/types";

/** How many names every faction's list holds. */
export const CITY_NAMES_PER_FACTION_V7 = 30;
/** A name is one capitalised word of 4 to 10 letters. */
export const CITY_NAME_PATTERN_V7 = /^[A-Z][a-z]{3,9}$/;

/**
 * City names (bead `pulp_wars-2yc.30`): thirty invented place names per
 * faction, in that faction's voice. A city takes one name from the list of
 * the faction it belongs to at the start (see `city-names-presentation-v7`)
 * and keeps it for the whole match.
 *
 * Adding a faction is one entry here: `satisfies Record<FactionIdV7, ...>`
 * fails the type check until every faction of the registry has a list, and
 * `tests/unit/city-names-presentation-v7.test.ts` holds every list to the
 * same rules (30 names, the pattern above, no name twice in the whole set,
 * no two names of a faction one letter apart).
 */
export const CITY_NAME_LISTS_V7 = Object.freeze({
  // Humans: storybook-medieval.
  ORIGINAL: Object.freeze([
    "Aldmere",
    "Brindle",
    "Corwick",
    "Dunholt",
    "Elmsby",
    "Fenwold",
    "Grenholt",
    "Hartlow",
    "Ivenmoor",
    "Kestrow",
    "Larkfen",
    "Mossgate",
    "Nolwick",
    "Orrowmead",
    "Pennow",
    "Quillham",
    "Rookwell",
    "Sedgeby",
    "Thistlow",
    "Umbrook",
    "Varnstead",
    "Wrenfold",
    "Yarrowick",
    "Ashmoot",
    "Bellory",
    "Cobbleton",
    "Dovemarch",
    "Emberlea",
    "Fallowmere",
    "Wendlow",
  ]),
  // Undead: hollow and mournful, spooky-fun.
  UNDEAD: Object.freeze([
    "Gloamwick",
    "Wistmoor",
    "Hushfen",
    "Sorrowfen",
    "Duskmere",
    "Palewater",
    "Sighlow",
    "Waxwane",
    "Lanthorn",
    "Wailmarsh",
    "Nomorrow",
    "Owlrest",
    "Tombly",
    "Cryptwell",
    "Shroudby",
    "Vesperine",
    "Ashenfold",
    "Mothwick",
    "Dimhollow",
    "Quietmoor",
    "Bonechime",
    "Weepwood",
    "Faintmere",
    "Gravelow",
    "Umbrance",
    "Fadelight",
    "Murkenby",
    "Hauntley",
    "Ebbingham",
    "Noctelle",
  ]),
  // Goblins: scrappy, guttural, comic.
  GOBLIN: Object.freeze([
    "Grubnak",
    "Snagrot",
    "Muckzug",
    "Skragg",
    "Bogwump",
    "Zogrit",
    "Klonkit",
    "Nubgrub",
    "Ratchug",
    "Splodgit",
    "Gribnok",
    "Dregmuk",
    "Slopwick",
    "Burzag",
    "Wonkpit",
    "Fizzgob",
    "Rustnik",
    "Tinkrot",
    "Urgzit",
    "Yobbok",
    "Mudgob",
    "Scrapzag",
    "Bashnik",
    "Dunkrag",
    "Kragmuk",
    "Oddnog",
    "Pilfrit",
    "Zagbot",
    "Hobnok",
    "Clatterog",
  ]),
  // Dinosaurs and their cavemen: primal, short syllables.
  DINOSAUR: Object.freeze([
    "Uggra",
    "Thogga",
    "Gronda",
    "Bomba",
    "Rokku",
    "Oomra",
    "Zugdar",
    "Thunka",
    "Mogru",
    "Dromu",
    "Hurrok",
    "Ragga",
    "Tuska",
    "Boruk",
    "Yagru",
    "Grumba",
    "Orrak",
    "Stomba",
    "Kullo",
    "Nargo",
    "Urdak",
    "Wogra",
    "Chomra",
    "Gorrum",
    "Tarrok",
    "Mokko",
    "Ruggu",
    "Hoonga",
    "Zarna",
    "Dakku",
  ]),
  // Martians: 1950s pulp science fiction, clipped, with the odd X, Z or K.
  MARTIAN: Object.freeze([
    "Zorvex",
    "Xenth",
    "Kazith",
    "Vextor",
    "Zyloth",
    "Quarn",
    "Ixara",
    "Nebrix",
    "Kryzel",
    "Xantik",
    "Zendrak",
    "Orbik",
    "Tyvox",
    "Vornak",
    "Kelzo",
    "Axilon",
    "Zetarn",
    "Polzak",
    "Ralux",
    "Kronyx",
    "Xibon",
    "Marzek",
    "Voltak",
    "Zakrel",
    "Ektor",
    "Quasik",
    "Ulmex",
    "Jexol",
    "Trizon",
    "Oxtar",
  ]),
  // Ice Folk: cold, soft, northern.
  ICE_FOLK: Object.freeze([
    "Snovik",
    "Frelund",
    "Hvitna",
    "Isbrek",
    "Kaldmir",
    "Njora",
    "Rimfall",
    "Solvhem",
    "Tindra",
    "Ulvsted",
    "Vinterby",
    "Yrsel",
    "Fjellow",
    "Glimra",
    "Haldrim",
    "Lumivik",
    "Mjolka",
    "Norrlys",
    "Ostrim",
    "Skalda",
    "Thawen",
    "Elsken",
    "Brisund",
    "Drivna",
    "Kvelda",
    "Aurvik",
    "Sneholm",
    "Vettra",
    "Hjorna",
    "Isalund",
  ]),
  // Dwarves: sturdy, steam and forge, heavy on consonants.
  DWARF: Object.freeze([
    "Brassgard",
    "Korrhold",
    "Durnbolt",
    "Grundvalv",
    "Stokvar",
    "Anvildur",
    "Borzund",
    "Thrumgar",
    "Cogdrum",
    "Hamrok",
    "Ferrund",
    "Krundle",
    "Rivetholm",
    "Skorrak",
    "Tolgrim",
    "Vulkrad",
    "Brakkun",
    "Dorrim",
    "Gandrik",
    "Maldrum",
    "Nargrund",
    "Pistonak",
    "Rukstad",
    "Smeltkar",
    "Gyrhald",
    "Bolgrum",
    "Kettrik",
    "Dromnar",
    "Zundak",
    "Welbrok",
  ]),
  // Candy: sweet and bouncy.
  CANDY: Object.freeze([
    "Bonbella",
    "Toffeny",
    "Sprinkel",
    "Fizzamint",
    "Gumdale",
    "Marzipop",
    "Jellywick",
    "Caramby",
    "Lollibee",
    "Mallowick",
    "Sucrelle",
    "Nougaline",
    "Taffywell",
    "Dulcette",
    "Glazeby",
    "Pralina",
    "Fudgley",
    "Treacleby",
    "Mintaloo",
    "Bubbleigh",
    "Cocoadell",
    "Honeyhop",
    "Sherbury",
    "Wafferly",
    "Icingham",
    "Plumkin",
    "Swirlipop",
    "Crumbelow",
    "Tartley",
    "Butterby",
  ]),
} as const satisfies Readonly<Record<FactionIdV7, readonly string[]>>);
