/**
 * Settlement ground-shadow measurement (bead pulp_wars-2yc.12). Measures
 * where every city and village sprite of the live look meets the ground
 * (scripts/art/settlement-shadows/measure.ts), and writes the table the
 * board's settlement shadow is fitted from:
 *
 *   src/render/canvas/settlement-shadow-measurements-v7.generated.ts
 *
 * One entry per settlement raster the live look resolves first (the
 * cities of every faction at art levels 1 to 3, and the Village), keyed
 * by asset id. How a shadow is derived from a measurement is in
 * src/render/canvas/settlement-shadow-v7.ts.
 *
 * Usage: npm run art:settlement-shadows-measure [-- --check]
 *
 * `--check` writes nothing and fails when the checked-in table differs from
 * the masters. No PixelLab call is made.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import prettier from "prettier";
import sharp from "sharp";
import { measureSettlementFootprintV7 } from "./settlement-shadows/measure";
import {
  liveSettlementAssetsV7,
  publicFileOfUrlV7,
} from "./unit-shadows/assets";

const ROOT = process.cwd();
const TABLE = path.join(
  ROOT,
  "src/render/canvas/settlement-shadow-measurements-v7.generated.ts",
);

async function render(): Promise<string> {
  const lines: string[] = [];
  for (const asset of await liveSettlementAssetsV7()) {
    const { data, info } = await sharp(publicFileOfUrlV7(asset.url))
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    if (info.width !== asset.width || info.height !== asset.height)
      throw new Error(`${asset.id}: master size differs from the manifest`);
    const footprint = measureSettlementFootprintV7({
      width: info.width,
      height: info.height,
      data: new Uint8Array(data),
    });
    lines.push(
      `  ${JSON.stringify(asset.id)}: ${JSON.stringify({
        subject: asset.subject,
        width: asset.width,
        height: asset.height,
        ...footprint,
      })},`,
    );
  }
  const source = `// Generated by scripts/art/settlement-shadow-measure.ts (npm run art:settlement-shadows-measure). Do not edit by hand.
import type { ArtSubjectV7 } from "../../assets/chibi-art-v7";

/**
 * Where a city or village sprite of the live look meets the ground, in
 * master pixels from its canvas's top-left corner (bead pulp_wars-2yc.12):
 * the contact line (one past the lowest opaque row), the left and
 * one-past-right ends of the footprint with the ground line at each end,
 * and how full the sprite's lower outline is between them (1 a round
 * ground, about 0.7 a diamond). See
 * scripts/art/settlement-shadows/measure.ts.
 */
export interface SettlementShadowMeasurementV7 {
  readonly subject: ArtSubjectV7;
  readonly width: number;
  readonly height: number;
  readonly contactY: number;
  readonly left: number;
  readonly right: number;
  readonly leftY: number;
  readonly rightY: number;
  readonly fullness: number;
}

/** Keyed by the id of the measured raster. */
export const SETTLEMENT_SHADOW_MEASUREMENTS_V7: Readonly<
  Record<string, SettlementShadowMeasurementV7>
> = {
${lines.join("\n")}
};
`;
  const config = (await prettier.resolveConfig(TABLE)) ?? {};
  return prettier.format(source, { ...config, filepath: TABLE });
}

const output = await render();
if (process.argv.includes("--check")) {
  const current = await readFile(TABLE, "utf8").catch(() => "");
  if (current !== output) {
    console.error(
      `${path.relative(ROOT, TABLE)} is stale: run npm run art:settlement-shadows-measure`,
    );
    process.exit(1);
  }
  console.log(`${path.relative(ROOT, TABLE)} matches the masters`);
} else {
  await writeFile(TABLE, output);
  console.log(`wrote ${path.relative(ROOT, TABLE)}`);
}
