/**
 * Unit ground-shadow measurement (bead pulp_wars-jg1). Measures where every
 * unit sprite of the live look touches the ground and how wide it is there
 * (scripts/art/unit-shadows/measure.ts), and writes the table the board's
 * ground shadow and ready ring are anchored from:
 *
 *   src/render/canvas/unit-shadow-measurements-v7.generated.ts
 *
 * One entry per `UNIT:` subject of the live direction art registry (the
 * raster the live look resolves first). How a shadow is derived from a
 * measurement, and which units fly or hover, is hand-checked in
 * src/render/canvas/unit-shadows-v7.ts.
 *
 * Usage: npm run art:unit-shadows-measure [-- --check]
 *
 * `--check` writes nothing and fails when the checked-in table differs from
 * the masters. No PixelLab call is made.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import prettier from "prettier";
import sharp from "sharp";
import { liveUnitAssetsV7, publicFileOfUrlV7 } from "./unit-shadows/assets";
import {
  BASE_BAND_ROWS_V7,
  FOOT_BAND_ROWS_V7,
  measureUnitFootprintV7,
} from "./unit-shadows/measure";

const ROOT = process.cwd();
const TABLE = path.join(
  ROOT,
  "src/render/canvas/unit-shadow-measurements-v7.generated.ts",
);

async function render(): Promise<string> {
  const lines: string[] = [];
  for (const asset of await liveUnitAssetsV7()) {
    const { data, info } = await sharp(publicFileOfUrlV7(asset.url))
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    if (info.width !== asset.width || info.height !== asset.height)
      throw new Error(`${asset.id}: master size differs from the manifest`);
    const footprint = measureUnitFootprintV7({
      width: info.width,
      height: info.height,
      data: new Uint8Array(data),
    });
    lines.push(
      `  ${JSON.stringify(asset.subject)}: ${JSON.stringify({
        assetId: asset.id,
        assetClass: asset.assetClass,
        width: asset.width,
        height: asset.height,
        contactY: footprint.contactY,
        footLeft: footprint.footLeft,
        footRight: footprint.footRight,
        baseLeft: footprint.baseLeft,
        baseRight: footprint.baseRight,
      })},`,
    );
  }
  const source = `// Generated by scripts/art/unit-shadow-measure.ts (npm run art:unit-shadows-measure). Do not edit by hand.
import type { ArtSubjectV7, ChibiAssetClassV7 } from "../../assets/chibi-art-v7";

/**
 * Where a unit sprite of the live look touches the ground, in master
 * pixels from its canvas's top-left corner (bead pulp_wars-jg1): the
 * contact line (one past the lowest opaque row), the opaque extent of the
 * feet (the ${FOOT_BAND_ROWS_V7} rows above it) and of the lower body (the ${BASE_BAND_ROWS_V7} rows above
 * it). See scripts/art/unit-shadows/measure.ts.
 */
export interface UnitShadowMeasurementV7 {
  readonly assetId: string;
  readonly assetClass: ChibiAssetClassV7;
  readonly width: number;
  readonly height: number;
  readonly contactY: number;
  readonly footLeft: number;
  readonly footRight: number;
  readonly baseLeft: number;
  readonly baseRight: number;
}

export const UNIT_SHADOW_MEASUREMENTS_V7: Readonly<
  Partial<Record<ArtSubjectV7, UnitShadowMeasurementV7>>
> = {
${lines.join("\n")}
};
`;
  const config = (await prettier.resolveConfig(TABLE)) ?? {};
  return prettier.format(source, { ...config, filepath: TABLE });
}

const output = await render();
if (process.argv.includes("--check")) {
  const current = await readFile(TABLE, "utf8").catch(() => "");
  if (current !== output) {
    console.error(
      `${path.relative(ROOT, TABLE)} is stale: run npm run art:unit-shadows-measure`,
    );
    process.exit(1);
  }
  console.log(`${path.relative(ROOT, TABLE)} matches the masters`);
} else {
  await writeFile(TABLE, output);
  console.log(`wrote ${path.relative(ROOT, TABLE)}`);
}
