import type { SCENARIO_HELPERS_V7 } from "./undead-tuning-analysis-v7";

/**
 * The played scenarios of the Undead pass (`pulp_wars-w49.13`,
 * docs/product/RULESET_7_TUNING_UNDEAD.md section 2): the mechanics a
 * matchup matrix cannot show. `play` resolves listed commands; `battle`
 * plays whole turns by a fixed script (stated in each title). Every tile is
 * open Grass unless the scenario says otherwise.
 */
export function undeadScenariosV7(h: typeof SCENARIO_HELPERS_V7): string[] {
  const { play, battle, attack, frenzy, wailStep, raise, devour, at } = h;
  const { endTurn, move, note, tend } = h;
  const row = (
    seat: number,
    role: Parameters<typeof play>[2][number]["role"],
    y: number,
    xs: readonly number[],
    extra: { readonly hp?: number } = {},
  ) => xs.map((x) => ({ seat, role, at: at(x, y), ...extra }));
  const lines: string[] = [];

  lines.push(
    "#### The Zombie wave",
    "",
    ...battle(
      "Five Zombies walk into five Fighters that stand and fight (15 Coins against 10; the Undead move first, two tiles away)",
      ["UNDEAD", "ORIGINAL"],
      [
        ...row(0, "GUARD", 3, [2, 3, 4, 5, 6]),
        ...row(1, "FIGHTER", 1, [2, 3, 4, 5, 6]),
      ],
      [{ mode: "ADVANCE" }, { mode: "HOLD" }],
      12,
    ),
    ...battle(
      "The same five Zombies into three Fighters with three Marksmen behind them (15 Coins against 18): the Fighters hit only to kill, the Marksmen shoot, nobody steps back",
      ["UNDEAD", "ORIGINAL"],
      [
        ...row(0, "GUARD", 4, [2, 3, 4, 5, 6]),
        ...row(1, "FIGHTER", 2, [3, 4, 5]),
        ...row(1, "MARKSMAN", 1, [3, 4, 5]),
      ],
      [{ mode: "ADVANCE" }, { mode: "SHOOT" }],
      12,
    ),
    ...battle(
      "Five Zombies into six Marksmen that step back from a Zombie beside them and shoot (15 Coins against 24)",
      ["UNDEAD", "ORIGINAL"],
      [
        ...row(0, "GUARD", 6, [2, 3, 4, 5, 6]),
        ...row(1, "MARKSMAN", 3, [2, 3, 4, 5, 6, 7]),
      ],
      [{ mode: "ADVANCE" }, { mode: "KITE" }],
      12,
    ),
    ...battle(
      "Three Zombies and four Skeletons (17 Coins) into three Fighters and three Marksmen (18 Coins), who shoot and hit only to kill",
      ["UNDEAD", "ORIGINAL"],
      [
        ...row(0, "GUARD", 4, [3, 4, 5]),
        ...row(0, "FIGHTER", 5, [2, 3, 5, 6]),
        ...row(1, "FIGHTER", 2, [3, 4, 5]),
        ...row(1, "MARKSMAN", 1, [3, 4, 5]),
      ],
      [{ mode: "ADVANCE" }, { mode: "SHOOT" }],
      12,
    ),
    ...battle(
      "Seven Skeletons (14 Coins) into six Marksmen that step back and shoot (24 Coins)",
      ["UNDEAD", "ORIGINAL"],
      [
        ...row(0, "FIGHTER", 6, [2, 3, 4, 5, 6, 7, 8]),
        ...row(1, "MARKSMAN", 3, [2, 3, 4, 5, 6, 7]),
      ],
      [{ mode: "ADVANCE" }, { mode: "KITE" }],
      12,
    ),
    "",
    "#### Bite, then kill",
    "",
    ...play(
      "A Zombie that stands beside a Fighter bites it; a Skeleton steps up and finishes it",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "GUARD", at: at(4, 3), tag: "zombie" },
        { seat: 0, role: "FIGHTER", at: at(6, 4), tag: "skeleton" },
        { seat: 0, role: "FIGHTER", at: at(3, 4), tag: "skeleton2" },
        { seat: 1, role: "FIGHTER", at: at(4, 2), tag: "fighter" },
      ],
      [
        attack("zombie", "fighter"),
        move("skeleton", at(5, 3)),
        attack("skeleton", "fighter"),
        move("skeleton2", at(3, 3)),
        attack("skeleton2", "fighter"),
      ],
    ),
    ...play(
      "A Zombie bites a Knight; a Ghoul steps up beside it (one tile: no Charge) and strikes with Carrion; a second Ghoul stands by",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "GUARD", at: at(4, 3), tag: "zombie" },
        { seat: 0, role: "RAIDER", at: at(6, 4), tag: "ghoul" },
        { seat: 0, role: "RAIDER", at: at(2, 4), tag: "ghoul2" },
        { seat: 1, role: "KNIGHT", at: at(4, 2), tag: "knight" },
      ],
      [
        attack("zombie", "knight"),
        move("ghoul", at(5, 3)),
        attack("ghoul", "knight"),
        move("ghoul2", at(2, 3), at(3, 2)),
        attack("ghoul2", "knight"),
      ],
    ),
    ...play(
      "A Zombie bites a wounded Marksman, and a Banshee's Wail finishes it: whatever kills a Bitten unit, it rises",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "GUARD", at: at(4, 3), tag: "zombie" },
        { seat: 0, role: "MARKSMAN", at: at(6, 3), tag: "banshee" },
        { seat: 1, role: "MARKSMAN", at: at(4, 2), hp: 8, tag: "marksman" },
      ],
      [attack("zombie", "marksman"), wailStep("banshee")],
    ),
    "",
    "#### The Lich and the Banshees",
    "",
    ...play(
      "With Pestilence: a Lich fires at the Swordsman in the middle of a line of five (Guard, Marksman, Swordsman, Fighter, Catapult behind); two Banshees step up and Wail; the Humans do nothing for three turns",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 0, role: "MARKSMAN", at: at(3, 5), tag: "b1" },
        { seat: 0, role: "MARKSMAN", at: at(5, 5), tag: "b2" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
        { seat: 1, role: "FIGHTER", at: at(5, 2) },
        { seat: 1, role: "MARKSMAN", at: at(3, 1) },
        { seat: 1, role: "CATAPULT", at: at(4, 1) },
      ],
      [
        attack("lich", "swordsman"),
        move("b1", at(3, 4)),
        wailStep("b1"),
        move("b2", at(5, 4)),
        wailStep("b2"),
        endTurn,
        note("The Humans' turn starts: Plague"),
        endTurn,
        attack("lich", "swordsman"),
        wailStep("b1"),
        wailStep("b2"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        wailStep("b1"),
        wailStep("b2"),
        endTurn,
      ],
      { pestilence: true },
    ),
    ...play(
      "The same without Pestilence (every Lich until its owner has researched Explosives): the shot and the splash, and no Plague",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 0, role: "MARKSMAN", at: at(3, 5), tag: "b1" },
        { seat: 0, role: "MARKSMAN", at: at(5, 5), tag: "b2" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
        { seat: 1, role: "FIGHTER", at: at(5, 2) },
        { seat: 1, role: "MARKSMAN", at: at(3, 1) },
        { seat: 1, role: "CATAPULT", at: at(4, 1) },
      ],
      [
        attack("lich", "swordsman"),
        move("b1", at(3, 4)),
        wailStep("b1"),
        move("b2", at(5, 4)),
        wailStep("b2"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        wailStep("b1"),
        wailStep("b2"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        wailStep("b1"),
        wailStep("b2"),
        endTurn,
      ],
    ),
    ...play(
      "The Lich alone on the same line, with Pestilence, for three turns (no Banshee)",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
        { seat: 1, role: "FIGHTER", at: at(5, 2) },
        { seat: 1, role: "MARKSMAN", at: at(3, 1) },
        { seat: 1, role: "CATAPULT", at: at(4, 1) },
      ],
      [
        attack("lich", "swordsman"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        endTurn,
      ],
      { pestilence: true },
    ),
    ...play(
      "The Lich alone on the same line, without Pestilence, for three turns",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
        { seat: 1, role: "FIGHTER", at: at(5, 2) },
        { seat: 1, role: "MARKSMAN", at: at(3, 1) },
        { seat: 1, role: "CATAPULT", at: at(4, 1) },
      ],
      [
        attack("lich", "swordsman"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        endTurn,
        endTurn,
        attack("lich", "swordsman"),
        endTurn,
      ],
    ),
    ...play(
      "The same Lich and Banshees on a line of three in a Forest (the Humans own Forestry; with Pestilence)",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 0, role: "MARKSMAN", at: at(3, 4), tag: "b1" },
        { seat: 0, role: "MARKSMAN", at: at(5, 4), tag: "b2" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
        { seat: 1, role: "FIGHTER", at: at(5, 2) },
      ],
      [attack("lich", "swordsman"), wailStep("b1"), wailStep("b2")],
      { forest: [at(3, 2), at(4, 2), at(5, 2)], pestilence: true },
    ),
    ...play(
      "A Captain beside the plagued line tends it (cures Plague and bites)",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
        { seat: 1, role: "FIGHTER", at: at(5, 2) },
        { seat: 1, role: "CAPTAIN", at: at(4, 1), tag: "captain" },
      ],
      [attack("lich", "swordsman"), endTurn, tend("captain"), endTurn, endTurn],
      { pestilence: true },
    ),
    ...play(
      "A Lich (with Pestilence) fires at a Bomb Chucker that stands between two Orc Brutes with a Goblin behind (Blast-proof)",
      ["UNDEAD", "GOBLIN"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "lich" },
        { seat: 1, role: "GUARD", at: at(3, 2) },
        { seat: 1, role: "MARKSMAN", at: at(4, 2), tag: "chucker" },
        { seat: 1, role: "GUARD", at: at(5, 2) },
        { seat: 1, role: "FIGHTER", at: at(4, 1) },
      ],
      [attack("lich", "chucker")],
      { pestilence: true },
    ),
    ...play(
      "A Human Catapult and a Lich in each other's range: whoever fires first",
      ["ORIGINAL", "UNDEAD"],
      [
        { seat: 0, role: "CATAPULT", at: at(4, 5), tag: "catapult" },
        { seat: 1, role: "CATAPULT", at: at(4, 2), tag: "lich" },
      ],
      [attack("catapult", "lich")],
    ),
    "",
    "#### The Vampire",
    "",
    ...play(
      "A Vampire rides round a Fighter and kills the Catapult behind it, and stays where the kill left it (the Vampire before the pass); in the Humans' turn two Marksmen shoot it",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "KNIGHT", at: at(8, 4), tag: "vampire" },
        { seat: 1, role: "FIGHTER", at: at(4, 3) },
        { seat: 1, role: "CATAPULT", at: at(6, 1), tag: "catapult" },
        { seat: 1, role: "MARKSMAN", at: at(4, 1), tag: "m1" },
        { seat: 1, role: "MARKSMAN", at: at(4, 0), tag: "m2" },
      ],
      [
        move("vampire", at(8, 3), at(7, 2)),
        attack("vampire", "catapult"),
        endTurn,
        move("m1", at(5, 1)),
        attack("m1", "vampire"),
        attack("m2", "vampire"),
      ],
    ),
    ...play(
      "The same strike, and the Vampire flies back three tiles (Escape): no Marksman reaches it",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "KNIGHT", at: at(8, 4), tag: "vampire" },
        { seat: 1, role: "FIGHTER", at: at(4, 3) },
        { seat: 1, role: "CATAPULT", at: at(6, 1), tag: "catapult" },
        { seat: 1, role: "MARKSMAN", at: at(4, 1), tag: "m1" },
        { seat: 1, role: "MARKSMAN", at: at(4, 0), tag: "m2" },
      ],
      [
        move("vampire", at(8, 3), at(7, 2)),
        attack("vampire", "catapult"),
        move("vampire", at(7, 2), at(8, 3), at(9, 4)),
        endTurn,
        move("m1", at(5, 2)),
        attack("m1", "vampire"),
      ],
    ),
    ...play(
      "A Vampire and a Catapult behind a line without a gap: the first hostile unit it comes beside ends its Move (zone of control), so it strikes the line and flies back",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "KNIGHT", at: at(4, 6), tag: "vampire" },
        { seat: 1, role: "FIGHTER", at: at(3, 3) },
        { seat: 1, role: "FIGHTER", at: at(4, 3), tag: "fighter" },
        { seat: 1, role: "FIGHTER", at: at(5, 3) },
        { seat: 1, role: "CATAPULT", at: at(4, 1), tag: "catapult" },
      ],
      [
        move("vampire", at(4, 5), at(4, 4)),
        attack("vampire", "catapult"),
        attack("vampire", "fighter"),
        move("vampire", at(4, 5), at(4, 6), at(4, 7)),
      ],
    ),
    ...play(
      "A Vampire at 4 HP drinks: a Swordsman, then (next turn) again",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "KNIGHT", at: at(4, 3), hp: 4, tag: "vampire" },
        { seat: 1, role: "SWORDSMAN", at: at(4, 2), tag: "swordsman" },
      ],
      [
        attack("vampire", "swordsman"),
        endTurn,
        endTurn,
        attack("vampire", "swordsman"),
      ],
    ),
    "",
    "#### The Necromancer",
    "",
    ...play(
      "A Necromancer beside three Graves raises them; next turn it calls Frenzy and the three Skeletons (5 HP) and a Zombie attack two Fighters",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "CAPTAIN", at: at(4, 4), tag: "necromancer" },
        { seat: 0, role: "GUARD", at: at(6, 3), tag: "zombie" },
        { seat: 1, role: "FIGHTER", at: at(4, 2), tag: "f1" },
        { seat: 1, role: "FIGHTER", at: at(6, 2), tag: "f2" },
      ],
      [
        raise("necromancer"),
        endTurn,
        endTurn,
        frenzy("necromancer"),
        attack("rise1", "f1"),
        attack("rise2", "f1"),
        attack("rise3", "f1"),
        attack("zombie", "f2"),
      ],
      { graves: [at(3, 3), at(4, 3), at(5, 3)] },
    ),
    ...play(
      "A wounded Ghoul (3 HP) moves two tiles onto a Grave and Devours it",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "RAIDER", at: at(4, 5), hp: 3, tag: "ghoul" },
        { seat: 1, role: "FIGHTER", at: at(4, 1) },
      ],
      [move("ghoul", at(4, 4), at(4, 3)), devour("ghoul")],
      { graves: [at(4, 3)] },
    ),
    "",
    "#### The Human Knight and the Zombies",
    "",
    ...play(
      "A Knight rides into three full Zombies standing together",
      ["ORIGINAL", "UNDEAD"],
      [
        { seat: 0, role: "KNIGHT", at: at(4, 4), tag: "knight" },
        { seat: 1, role: "GUARD", at: at(4, 3), tag: "z1" },
        { seat: 1, role: "GUARD", at: at(3, 2), tag: "z2" },
        { seat: 1, role: "GUARD", at: at(5, 2), tag: "z3" },
      ],
      [attack("knight", "z1"), attack("knight", "z2")],
    ),
    ...play(
      "A Marksman shoots the first Zombie, then the Knight: Zombie, a Zombie that has just risen (10 HP), a Banshee, a Lich",
      ["ORIGINAL", "UNDEAD"],
      [
        { seat: 0, role: "MARKSMAN", at: at(4, 6), tag: "marksman" },
        { seat: 0, role: "MARKSMAN", at: at(3, 6), tag: "marksman2" },
        { seat: 0, role: "KNIGHT", at: at(4, 5), tag: "knight" },
        { seat: 1, role: "GUARD", at: at(4, 4), tag: "z1" },
        { seat: 1, role: "GUARD", at: at(4, 3), hp: 10, tag: "z2" },
        { seat: 1, role: "MARKSMAN", at: at(4, 2), tag: "banshee" },
        { seat: 1, role: "CATAPULT", at: at(4, 1), tag: "lich" },
      ],
      [
        attack("marksman", "z1"),
        attack("marksman2", "z1"),
        attack("knight", "z1"),
        attack("knight", "z2"),
        attack("knight", "banshee"),
        attack("knight", "lich"),
      ],
    ),
    ...play(
      "Three Zombies answer a Knight that stopped beside them (it is bitten, and killed by the third: it rises)",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "GUARD", at: at(4, 3), hp: 6, tag: "z1" },
        { seat: 0, role: "GUARD", at: at(3, 3), tag: "z2" },
        { seat: 0, role: "GUARD", at: at(5, 3), tag: "z3" },
        { seat: 1, role: "KNIGHT", at: at(4, 4), hp: 10, tag: "knight" },
      ],
      [attack("z1", "knight"), attack("z2", "knight"), attack("z3", "knight")],
    ),
    "",
    "#### Goblins against Zombies",
    "",
    ...play(
      "Three Bomb Chuckers throw at the middle Zombie of three standing together",
      ["GOBLIN", "UNDEAD"],
      [
        { seat: 0, role: "MARKSMAN", at: at(3, 5), tag: "c1" },
        { seat: 0, role: "MARKSMAN", at: at(4, 5), tag: "c2" },
        { seat: 0, role: "MARKSMAN", at: at(5, 5), tag: "c3" },
        { seat: 1, role: "GUARD", at: at(3, 3) },
        { seat: 1, role: "GUARD", at: at(4, 3), tag: "zombie" },
        { seat: 1, role: "GUARD", at: at(5, 3) },
      ],
      [attack("c1", "zombie"), attack("c2", "zombie"), attack("c3", "zombie")],
    ),
    ...play(
      "A Rocket Cart with one Goblin beside the target and WAAAGH! fires at a Zombie; a Goblin Kabooms between two Zombies",
      ["GOBLIN", "UNDEAD"],
      [
        { seat: 0, role: "CAPTAIN", at: at(5, 6), tag: "warboss" },
        { seat: 0, role: "CATAPULT", at: at(4, 6), tag: "cart" },
        { seat: 0, role: "FIGHTER", at: at(4, 4), tag: "goblin" },
        { seat: 1, role: "GUARD", at: at(4, 3), tag: "zombie" },
        { seat: 1, role: "GUARD", at: at(5, 3) },
      ],
      [frenzy("warboss"), attack("cart", "zombie"), h.kaboom("goblin")],
    ),
    ...play(
      "Two Goblins (Gang Up) attack a Zombie: both are bitten",
      ["GOBLIN", "UNDEAD"],
      [
        { seat: 0, role: "FIGHTER", at: at(3, 4), tag: "g1" },
        { seat: 0, role: "FIGHTER", at: at(5, 4), tag: "g2" },
        { seat: 1, role: "GUARD", at: at(4, 3), tag: "zombie" },
      ],
      [attack("g1", "zombie"), attack("g2", "zombie")],
    ),
    "",
    "#### The Abomination",
    "",
    ...play(
      "An Abomination attacks a Fighter, and next turn a Marksman",
      ["UNDEAD", "ORIGINAL"],
      [
        { seat: 0, role: "JUGGERNAUT", at: at(4, 3), tag: "abomination" },
        { seat: 1, role: "FIGHTER", at: at(4, 2), tag: "fighter" },
        { seat: 1, role: "MARKSMAN", at: at(5, 2), tag: "marksman" },
      ],
      [
        attack("abomination", "fighter"),
        endTurn,
        endTurn,
        attack("abomination", "marksman"),
      ],
    ),
  );
  return lines;
}
