/// <reference types="vite/client" />
import type { ChibiArtAssetV7 } from "./chibi-art-v7";

/**
 * Accepted CHIBI art-set rasters for Ruleset 7 (?art=chibi). Batch beads add
 * entries here after review; every subject without an entry keeps rendering
 * its legacy asset at the chibi geometry. Rasters live under
 * public/assets/chibi/ and use chibiArtUrl so the Vite base path applies.
 * Contract: docs/art/CHIBI_ART_DIRECTION.md sections 3 and 4.
 */
export const CHIBI_ART_ASSETS_V7: readonly ChibiArtAssetV7[] = [
  // Batch 1 (pulp_wars-67q.3): terrain, Village, City 1-3, Fighter, Marksman.
  {
    id: "chibi-grass-1",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
  },
  {
    id: "chibi-grass-2",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-2.png"),
  },
  {
    id: "chibi-grass-3",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-3.png"),
  },
  {
    id: "chibi-forest-1",
    subject: "TERRAIN:FOREST",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-forest-1.png"),
  },
  {
    id: "chibi-forest-2",
    subject: "TERRAIN:FOREST",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-forest-2.png"),
  },
  {
    id: "chibi-mountain-1",
    subject: "TERRAIN:MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mountain-1.png"),
  },
  {
    id: "chibi-mountain-3",
    subject: "TERRAIN:MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mountain-3.png"),
  },
  {
    id: "chibi-shallow-water-1",
    subject: "TERRAIN:SHALLOW_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-shallow-water-1.png"),
  },
  {
    id: "chibi-shallow-water-2",
    subject: "TERRAIN:SHALLOW_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-shallow-water-2.png"),
  },
  {
    id: "chibi-deep-water-1",
    subject: "TERRAIN:DEEP_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-deep-water-1.png"),
  },
  {
    id: "chibi-deep-water-2",
    subject: "TERRAIN:DEEP_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-deep-water-2.png"),
  },
  {
    id: "chibi-village",
    subject: "SITE:VILLAGE",
    assetClass: "SETTLEMENT",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/settlements/chibi-village.png"),
  },
  {
    id: "chibi-city-1",
    subject: "CITY:1",
    assetClass: "SETTLEMENT",
    width: 88,
    height: 96,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-1.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-1.mask.png"),
  },
  {
    id: "chibi-city-2",
    subject: "CITY:2",
    assetClass: "SETTLEMENT",
    width: 96,
    height: 100,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-2.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-2.mask.png"),
  },
  {
    id: "chibi-city-3",
    subject: "CITY:3",
    assetClass: "SETTLEMENT",
    width: 96,
    height: 104,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-3.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-3.mask.png"),
  },
  {
    id: "chibi-fighter",
    subject: "UNIT:FIGHTER",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-fighter.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-fighter.mask.png"),
  },
  {
    id: "chibi-marksman",
    subject: "UNIT:MARKSMAN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-marksman.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-marksman.mask.png"),
  },
  // Batch 2 (pulp_wars-67q.5): the remaining land units.
  {
    id: "chibi-raider",
    subject: "UNIT:RAIDER",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-raider.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-raider.mask.png"),
  },
  {
    id: "chibi-guard",
    subject: "UNIT:GUARD",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-guard.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-guard.mask.png"),
  },
  {
    id: "chibi-captain",
    subject: "UNIT:CAPTAIN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-captain.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-captain.mask.png"),
  },
  {
    id: "chibi-catapult",
    subject: "UNIT:CATAPULT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-catapult.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-catapult.mask.png"),
  },
  {
    id: "chibi-knight",
    subject: "UNIT:KNIGHT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-knight.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-knight.mask.png"),
  },
  {
    id: "chibi-juggernaut",
    subject: "UNIT:JUGGERNAUT",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 104,
    url: chibiArtUrl("assets/chibi/units/chibi-juggernaut.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-juggernaut.mask.png"),
  },
  // Batch 3 (pulp_wars-67q.7): resources, Treasure, Farm, Lumber Camp, Mine,
  // Port and Monument. Resources and Treasure are unowned; improvements carry
  // an owner-colour roof, flag or banner through their masks.
  {
    id: "chibi-fruit",
    subject: "RESOURCE:FRUIT",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-fruit.png"),
  },
  {
    id: "chibi-fertile-ground",
    subject: "RESOURCE:FERTILE_GROUND",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-fertile-ground.png"),
  },
  {
    id: "chibi-game",
    subject: "RESOURCE:GAME",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-game.png"),
  },
  {
    id: "chibi-ore",
    subject: "RESOURCE:ORE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-ore.png"),
  },
  {
    id: "chibi-fish",
    subject: "RESOURCE:FISH",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-fish.png"),
  },
  {
    id: "chibi-pearls",
    subject: "RESOURCE:PEARLS",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-pearls.png"),
  },
  {
    id: "chibi-treasure",
    subject: "TREASURE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-treasure.png"),
  },
  {
    id: "chibi-farm",
    subject: "IMPROVEMENT:FARM",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-farm.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-farm.mask.png"),
  },
  {
    id: "chibi-lumber-camp",
    subject: "IMPROVEMENT:LUMBER_CAMP",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-lumber-camp.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/buildings/chibi-lumber-camp.mask.png",
    ),
  },
  {
    id: "chibi-port",
    subject: "IMPROVEMENT:PORT",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-port.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-port.mask.png"),
  },
  {
    id: "chibi-monument",
    subject: "IMPROVEMENT:MONUMENT",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-monument.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-monument.mask.png"),
  },
  {
    id: "chibi-mined-mountain-1",
    subject: "TERRAIN:MINED_MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mined-mountain-1.png"),
  },
  {
    id: "chibi-mined-mountain-2",
    subject: "TERRAIN:MINED_MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mined-mountain-2.png"),
  },
  // Batch 4 (pulp_wars-67q.9): the six processors with a masked red-roof or
  // red-cloth owner area, and the ships. Undead naval units reuse the ships.
  {
    id: "chibi-windmill",
    subject: "IMPROVEMENT:WINDMILL",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-windmill.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-windmill.mask.png"),
  },
  {
    id: "chibi-sawmill",
    subject: "IMPROVEMENT:SAWMILL",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-sawmill.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-sawmill.mask.png"),
  },
  {
    id: "chibi-forge",
    subject: "IMPROVEMENT:FORGE",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-forge.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-forge.mask.png"),
  },
  {
    id: "chibi-workshop",
    subject: "IMPROVEMENT:WORKSHOP",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-workshop.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-workshop.mask.png"),
  },
  {
    id: "chibi-market",
    subject: "IMPROVEMENT:MARKET",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-market.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-market.mask.png"),
  },
  {
    id: "chibi-shipyard",
    subject: "IMPROVEMENT:SHIPYARD",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-shipyard.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-shipyard.mask.png"),
  },
  {
    id: "chibi-patrol-boat",
    subject: "UNIT:PATROL_BOAT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-patrol-boat.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-patrol-boat.mask.png"),
  },
  {
    id: "chibi-battleship",
    subject: "UNIT:BATTLESHIP",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 96,
    url: chibiArtUrl("assets/chibi/units/chibi-battleship.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-battleship.mask.png"),
  },
  {
    id: "chibi-embarked-transport",
    subject: "UNIT:EMBARKED_TRANSPORT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 72,
    url: chibiArtUrl("assets/chibi/units/chibi-embarked-transport.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-embarked-transport.mask.png",
    ),
  },
  // Undead (pulp_wars-vkq.12): UNIT:UNDEAD:<ROLE> units and the Grave marker.
  {
    id: "chibi-undead-skeleton",
    subject: "UNIT:UNDEAD:FIGHTER",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-skeleton.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-skeleton.mask.png",
    ),
  },
  {
    id: "chibi-undead-ghoul",
    subject: "UNIT:UNDEAD:RAIDER",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-ghoul.png"),
    // 4 px right of the default so the cloak tip and front claw clear the
    // HP bar and seat badge.
    anchor: { x: 32, y: 48 },
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-undead-ghoul.mask.png"),
  },
  {
    id: "chibi-undead-banshee",
    subject: "UNIT:UNDEAD:MARKSMAN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-banshee.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-banshee.mask.png",
    ),
  },
  {
    id: "chibi-undead-zombie",
    subject: "UNIT:UNDEAD:GUARD",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-zombie.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-zombie.mask.png",
    ),
  },
  {
    id: "chibi-undead-necromancer",
    subject: "UNIT:UNDEAD:CAPTAIN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-necromancer.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-necromancer.mask.png",
    ),
  },
  {
    id: "chibi-undead-lich",
    subject: "UNIT:UNDEAD:CATAPULT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-lich.png"),
    // 7 px right of the default so the wide robe hem clears the seat badge.
    anchor: { x: 29, y: 48 },
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-undead-lich.mask.png"),
  },
  {
    id: "chibi-undead-vampire",
    subject: "UNIT:UNDEAD:KNIGHT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-vampire.png"),
    // 3 px right of the default so the left cape wing clears the HP bar.
    anchor: { x: 33, y: 48 },
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-vampire.mask.png",
    ),
  },
  {
    id: "chibi-undead-abomination",
    subject: "UNIT:UNDEAD:JUGGERNAUT",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 104,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-abomination.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-abomination.mask.png",
    ),
  },
  {
    id: "chibi-grave",
    subject: "GRAVE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-grave.png"),
  },
];

export function chibiArtUrl(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}
