/// <reference types="vite/client" />
import type { ChibiArtAssetV7 } from "./chibi-art-v7";

/**
 * Accepted CHIBI art-set rasters for Ruleset 7 (?art=chibi). Batch beads add
 * entries here after review; every subject without an entry keeps rendering
 * its legacy asset at the chibi geometry. Rasters live under
 * public/assets/chibi/ and use chibiArtUrl so the Vite base path applies.
 * Contract: docs/art/CHIBI_ART_DIRECTION.md sections 3 and 4.
 */
export const CHIBI_ART_ASSETS_V7: readonly ChibiArtAssetV7[] = [
  // Batch 1 (pulp_wars-67q.3): terrain, Village, City 1-3, Fighter, Marksman.
  {
    id: "chibi-grass-1",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
  },
  {
    id: "chibi-grass-2",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-2.png"),
  },
  {
    id: "chibi-grass-3",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-3.png"),
  },
  {
    id: "chibi-forest-1",
    subject: "TERRAIN:FOREST",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-forest-1.png"),
  },
  {
    id: "chibi-forest-2",
    subject: "TERRAIN:FOREST",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-forest-2.png"),
  },
  {
    id: "chibi-mountain-1",
    subject: "TERRAIN:MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mountain-1.png"),
  },
  {
    id: "chibi-mountain-3",
    subject: "TERRAIN:MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mountain-3.png"),
  },
  {
    id: "chibi-shallow-water-1",
    subject: "TERRAIN:SHALLOW_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-shallow-water-1.png"),
  },
  {
    id: "chibi-shallow-water-2",
    subject: "TERRAIN:SHALLOW_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-shallow-water-2.png"),
  },
  {
    id: "chibi-deep-water-1",
    subject: "TERRAIN:DEEP_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-deep-water-1.png"),
  },
  {
    id: "chibi-deep-water-2",
    subject: "TERRAIN:DEEP_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-deep-water-2.png"),
  },
  {
    id: "chibi-village",
    subject: "SITE:VILLAGE",
    assetClass: "SETTLEMENT",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/settlements/chibi-village.png"),
  },
  {
    id: "chibi-city-1",
    subject: "CITY:1",
    assetClass: "SETTLEMENT",
    width: 88,
    height: 96,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-1.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-1.mask.png"),
  },
  {
    id: "chibi-city-2",
    subject: "CITY:2",
    assetClass: "SETTLEMENT",
    width: 96,
    height: 100,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-2.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-2.mask.png"),
  },
  {
    id: "chibi-city-3",
    subject: "CITY:3",
    assetClass: "SETTLEMENT",
    width: 96,
    height: 104,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-3.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-3.mask.png"),
  },
  {
    id: "chibi-fighter",
    subject: "UNIT:FIGHTER",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-fighter.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-fighter.mask.png"),
  },
  {
    id: "chibi-marksman",
    subject: "UNIT:MARKSMAN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-marksman.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-marksman.mask.png"),
  },
  // Batch 2 (pulp_wars-67q.5): the remaining land units.
  {
    id: "chibi-raider",
    subject: "UNIT:RAIDER",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-raider.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-raider.mask.png"),
  },
  {
    id: "chibi-guard",
    subject: "UNIT:GUARD",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-guard.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-guard.mask.png"),
  },
  {
    id: "chibi-captain",
    subject: "UNIT:CAPTAIN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-captain.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-captain.mask.png"),
  },
  {
    id: "chibi-catapult",
    subject: "UNIT:CATAPULT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-catapult.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-catapult.mask.png"),
  },
  {
    id: "chibi-knight",
    subject: "UNIT:KNIGHT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-knight.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-knight.mask.png"),
  },
  {
    id: "chibi-juggernaut",
    subject: "UNIT:JUGGERNAUT",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 104,
    url: chibiArtUrl("assets/chibi/units/chibi-juggernaut.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-juggernaut.mask.png"),
  },
  // Batch 3 (pulp_wars-67q.7): resources, Treasure, Farm, Lumber Camp, Mine,
  // Port and Monument. Resources and Treasure are unowned; improvements carry
  // an owner-colour roof, flag or banner through their masks.
  {
    id: "chibi-fruit",
    subject: "RESOURCE:FRUIT",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-fruit.png"),
  },
  {
    id: "chibi-fertile-ground",
    subject: "RESOURCE:FERTILE_GROUND",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-fertile-ground.png"),
  },
  {
    id: "chibi-game",
    subject: "RESOURCE:GAME",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-game.png"),
  },
  {
    id: "chibi-ore",
    subject: "RESOURCE:ORE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-ore.png"),
  },
  {
    id: "chibi-fish",
    subject: "RESOURCE:FISH",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-fish.png"),
  },
  {
    id: "chibi-pearls",
    subject: "RESOURCE:PEARLS",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-pearls.png"),
  },
  {
    id: "chibi-treasure",
    subject: "TREASURE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-treasure.png"),
  },
  {
    id: "chibi-farm",
    subject: "IMPROVEMENT:FARM",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-farm.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-farm.mask.png"),
  },
  {
    id: "chibi-lumber-camp",
    subject: "IMPROVEMENT:LUMBER_CAMP",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-lumber-camp.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/buildings/chibi-lumber-camp.mask.png",
    ),
  },
  {
    id: "chibi-port",
    subject: "IMPROVEMENT:PORT",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-port.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-port.mask.png"),
  },
  {
    id: "chibi-monument",
    subject: "IMPROVEMENT:MONUMENT",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-monument.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-monument.mask.png"),
  },
  {
    id: "chibi-mined-mountain-1",
    subject: "TERRAIN:MINED_MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mined-mountain-1.png"),
  },
  {
    id: "chibi-mined-mountain-2",
    subject: "TERRAIN:MINED_MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mined-mountain-2.png"),
  },
];

export function chibiArtUrl(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}
