/// <reference types="vite/client" />
import type { ChibiArtAssetV7 } from "./chibi-art-v7";

/**
 * Accepted CHIBI art-set rasters for Ruleset 7 (?art=chibi). Batch beads add
 * entries here after review; every subject without an entry keeps rendering
 * its legacy asset at the chibi geometry. Rasters live under
 * public/assets/chibi/ and use chibiArtUrl so the Vite base path applies.
 * Contract: docs/art/CHIBI_ART_DIRECTION.md sections 3 and 4.
 */
export const CHIBI_ART_ASSETS_V7: readonly ChibiArtAssetV7[] = [
  // Batch 1 (pulp_wars-67q.3): terrain, Village, City 1-3, Fighter, Marksman.
  {
    id: "chibi-grass-1",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
  },
  {
    id: "chibi-grass-2",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-2.png"),
  },
  {
    id: "chibi-grass-3",
    subject: "TERRAIN:GRASS",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-grass-3.png"),
  },
  {
    id: "chibi-forest-1",
    subject: "TERRAIN:FOREST",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-forest-1.png"),
    layers: {
      bodyUrl: chibiArtUrl("assets/chibi/terrain/chibi-forest-1.body.png"),
      groundUrl: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
    },
  },
  {
    id: "chibi-forest-2",
    subject: "TERRAIN:FOREST",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-forest-2.png"),
    layers: {
      bodyUrl: chibiArtUrl("assets/chibi/terrain/chibi-forest-2.body.png"),
      groundUrl: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
    },
  },
  {
    id: "chibi-mountain-1",
    subject: "TERRAIN:MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mountain-1.png"),
    layers: {
      bodyUrl: chibiArtUrl("assets/chibi/terrain/chibi-mountain-1.body.png"),
      groundUrl: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
    },
  },
  {
    id: "chibi-mountain-3",
    subject: "TERRAIN:MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mountain-3.png"),
    layers: {
      bodyUrl: chibiArtUrl("assets/chibi/terrain/chibi-mountain-3.body.png"),
      groundUrl: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
    },
  },
  {
    id: "chibi-shallow-water-1",
    subject: "TERRAIN:SHALLOW_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-shallow-water-1.png"),
  },
  {
    id: "chibi-shallow-water-2",
    subject: "TERRAIN:SHALLOW_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-shallow-water-2.png"),
  },
  {
    id: "chibi-deep-water-1",
    subject: "TERRAIN:DEEP_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-deep-water-1.png"),
  },
  {
    id: "chibi-deep-water-2",
    subject: "TERRAIN:DEEP_WATER",
    assetClass: "TERRAIN",
    width: 80,
    height: 80,
    url: chibiArtUrl("assets/chibi/terrain/chibi-deep-water-2.png"),
  },
  {
    id: "chibi-village",
    subject: "SITE:VILLAGE",
    assetClass: "SETTLEMENT",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/settlements/chibi-village.png"),
  },
  {
    id: "chibi-city-1",
    subject: "CITY:1",
    assetClass: "SETTLEMENT",
    width: 88,
    height: 96,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-1.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-1.mask.png"),
  },
  {
    id: "chibi-city-2",
    subject: "CITY:2",
    assetClass: "SETTLEMENT",
    width: 96,
    height: 100,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-2.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-2.mask.png"),
  },
  {
    id: "chibi-city-3",
    subject: "CITY:3",
    assetClass: "SETTLEMENT",
    width: 96,
    height: 104,
    url: chibiArtUrl("assets/chibi/settlements/chibi-city-3.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/settlements/chibi-city-3.mask.png"),
  },
  {
    id: "chibi-fighter",
    subject: "UNIT:FIGHTER",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-fighter.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-fighter.mask.png"),
  },
  {
    id: "chibi-marksman",
    subject: "UNIT:MARKSMAN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-marksman.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-marksman.mask.png"),
  },
  // Batch 2 (pulp_wars-67q.5): the remaining land units.
  {
    id: "chibi-raider",
    subject: "UNIT:RAIDER",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-raider.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-raider.mask.png"),
  },
  {
    id: "chibi-guard",
    subject: "UNIT:GUARD",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-guard.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-guard.mask.png"),
  },
  {
    id: "chibi-captain",
    subject: "UNIT:CAPTAIN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-captain.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-captain.mask.png"),
  },
  {
    id: "chibi-catapult",
    subject: "UNIT:CATAPULT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-catapult.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-catapult.mask.png"),
  },
  {
    id: "chibi-knight",
    subject: "UNIT:KNIGHT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-knight.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-knight.mask.png"),
  },
  {
    id: "chibi-juggernaut",
    subject: "UNIT:JUGGERNAUT",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 104,
    url: chibiArtUrl("assets/chibi/units/chibi-juggernaut.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-juggernaut.mask.png"),
  },
  // Batch 3 (pulp_wars-67q.7): resources, Treasure, Farm, Lumber Camp, Mine,
  // Port and Monument. Resources and Treasure are unowned; improvements carry
  // an owner-colour roof, flag or banner through their masks.
  {
    id: "chibi-fruit",
    subject: "RESOURCE:FRUIT",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-fruit.png"),
  },
  {
    id: "chibi-fertile-ground",
    subject: "RESOURCE:FERTILE_GROUND",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-fertile-ground.png"),
  },
  {
    id: "chibi-game",
    subject: "RESOURCE:GAME",
    assetClass: "RESOURCE",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/resources/chibi-game.png"),
  },
  {
    // Bead pulp_wars-pa3 (batch ore-2): copper-orange Ore that reads on the
    // grey Mountains; it replaces batch 3's chibi-ore.
    id: "chibi-ore-2",
    subject: "RESOURCE:ORE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-ore-2.png"),
  },
  {
    id: "chibi-fish",
    subject: "RESOURCE:FISH",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-fish.png"),
  },
  {
    id: "chibi-pearls",
    subject: "RESOURCE:PEARLS",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-pearls.png"),
  },
  {
    id: "chibi-treasure",
    subject: "TREASURE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-treasure.png"),
  },
  {
    id: "chibi-farm",
    subject: "IMPROVEMENT:FARM",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-farm.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-farm.mask.png"),
  },
  {
    id: "chibi-lumber-camp",
    subject: "IMPROVEMENT:LUMBER_CAMP",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-lumber-camp.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/buildings/chibi-lumber-camp.mask.png",
    ),
  },
  {
    id: "chibi-port",
    subject: "IMPROVEMENT:PORT",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-port.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-port.mask.png"),
  },
  {
    id: "chibi-monument",
    subject: "IMPROVEMENT:MONUMENT",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-monument.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-monument.mask.png"),
  },
  {
    id: "chibi-mined-mountain-1",
    subject: "TERRAIN:MINED_MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mined-mountain-1.png"),
    layers: {
      bodyUrl: chibiArtUrl(
        "assets/chibi/terrain/chibi-mined-mountain-1.body.png",
      ),
      groundUrl: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
    },
  },
  {
    id: "chibi-mined-mountain-2",
    subject: "TERRAIN:MINED_MOUNTAIN",
    assetClass: "TALL_TERRAIN",
    width: 80,
    height: 104,
    url: chibiArtUrl("assets/chibi/terrain/chibi-mined-mountain-2.png"),
    layers: {
      bodyUrl: chibiArtUrl(
        "assets/chibi/terrain/chibi-mined-mountain-2.body.png",
      ),
      groundUrl: chibiArtUrl("assets/chibi/terrain/chibi-grass-1.png"),
    },
  },
  // Batch 4 (pulp_wars-67q.9): the six processors with a masked red-roof or
  // red-cloth owner area, and the ships. Undead naval units reuse the ships.
  {
    id: "chibi-windmill",
    subject: "IMPROVEMENT:WINDMILL",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-windmill.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-windmill.mask.png"),
  },
  {
    id: "chibi-sawmill",
    subject: "IMPROVEMENT:SAWMILL",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-sawmill.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-sawmill.mask.png"),
  },
  {
    id: "chibi-forge",
    subject: "IMPROVEMENT:FORGE",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-forge.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-forge.mask.png"),
  },
  {
    id: "chibi-workshop",
    subject: "IMPROVEMENT:WORKSHOP",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-workshop.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-workshop.mask.png"),
  },
  {
    id: "chibi-market",
    subject: "IMPROVEMENT:MARKET",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-market.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-market.mask.png"),
  },
  {
    id: "chibi-shipyard",
    subject: "IMPROVEMENT:SHIPYARD",
    assetClass: "BUILDING",
    width: 80,
    height: 88,
    url: chibiArtUrl("assets/chibi/buildings/chibi-shipyard.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/buildings/chibi-shipyard.mask.png"),
  },
  {
    id: "chibi-patrol-boat",
    subject: "UNIT:PATROL_BOAT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-patrol-boat.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-patrol-boat.mask.png"),
  },
  {
    id: "chibi-battleship",
    subject: "UNIT:BATTLESHIP",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 96,
    url: chibiArtUrl("assets/chibi/units/chibi-battleship.png"),
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-battleship.mask.png"),
  },
  {
    id: "chibi-embarked-transport",
    subject: "UNIT:EMBARKED_TRANSPORT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 72,
    url: chibiArtUrl("assets/chibi/units/chibi-embarked-transport.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-embarked-transport.mask.png",
    ),
  },
  // Undead (pulp_wars-vkq.12): UNIT:UNDEAD:<ROLE> units and the Grave marker.
  {
    id: "chibi-undead-skeleton",
    subject: "UNIT:UNDEAD:FIGHTER",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-skeleton.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-skeleton.mask.png",
    ),
  },
  {
    id: "chibi-undead-ghoul",
    subject: "UNIT:UNDEAD:RAIDER",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-ghoul.png"),
    // 4 px right of the default so the cloak tip and front claw clear the
    // HP bar and seat badge.
    anchor: { x: 32, y: 48 },
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-undead-ghoul.mask.png"),
  },
  {
    id: "chibi-undead-banshee",
    subject: "UNIT:UNDEAD:MARKSMAN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-banshee.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-banshee.mask.png",
    ),
  },
  {
    id: "chibi-undead-zombie",
    subject: "UNIT:UNDEAD:GUARD",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-zombie.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-zombie.mask.png",
    ),
  },
  {
    id: "chibi-undead-necromancer",
    subject: "UNIT:UNDEAD:CAPTAIN",
    assetClass: "STANDARD_UNIT",
    width: 56,
    height: 80,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-necromancer.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-necromancer.mask.png",
    ),
  },
  {
    id: "chibi-undead-lich",
    subject: "UNIT:UNDEAD:CATAPULT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-lich.png"),
    // 7 px right of the default so the wide robe hem clears the seat badge.
    anchor: { x: 29, y: 48 },
    ownerMaskUrl: chibiArtUrl("assets/chibi/units/chibi-undead-lich.mask.png"),
  },
  {
    id: "chibi-undead-vampire",
    subject: "UNIT:UNDEAD:KNIGHT",
    assetClass: "LARGE_UNIT",
    width: 72,
    height: 88,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-vampire.png"),
    // 3 px right of the default so the left cape wing clears the HP bar.
    anchor: { x: 33, y: 48 },
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-vampire.mask.png",
    ),
  },
  {
    id: "chibi-undead-abomination",
    subject: "UNIT:UNDEAD:JUGGERNAUT",
    assetClass: "GIANT_UNIT",
    width: 88,
    height: 104,
    url: chibiArtUrl("assets/chibi/units/chibi-undead-abomination.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/units/chibi-undead-abomination.mask.png",
    ),
  },
  {
    id: "chibi-grave",
    subject: "GRAVE",
    assetClass: "RESOURCE",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/resources/chibi-grave.png"),
  },
  // Batch 5 (pulp_wars-67q.11): interface portraits and icons (DOM only).
  {
    id: "chibi-portrait-battleship",
    subject: "PORTRAIT:BATTLESHIP",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-battleship.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-battleship.mask.png",
    ),
  },
  {
    id: "chibi-portrait-captain",
    subject: "PORTRAIT:CAPTAIN",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-captain.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-captain.mask.png",
    ),
  },
  {
    id: "chibi-portrait-catapult",
    subject: "PORTRAIT:CATAPULT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-catapult.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-catapult.mask.png",
    ),
  },
  {
    id: "chibi-portrait-fighter",
    subject: "PORTRAIT:FIGHTER",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-fighter.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-fighter.mask.png",
    ),
  },
  {
    id: "chibi-portrait-guard",
    subject: "PORTRAIT:GUARD",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-guard.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-guard.mask.png",
    ),
  },
  {
    id: "chibi-portrait-juggernaut",
    subject: "PORTRAIT:JUGGERNAUT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-juggernaut.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-juggernaut.mask.png",
    ),
  },
  {
    id: "chibi-portrait-knight",
    subject: "PORTRAIT:KNIGHT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-knight.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-knight.mask.png",
    ),
  },
  {
    id: "chibi-portrait-marksman",
    subject: "PORTRAIT:MARKSMAN",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-marksman.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-marksman.mask.png",
    ),
  },
  {
    id: "chibi-portrait-patrol-boat",
    subject: "PORTRAIT:PATROL_BOAT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-patrol-boat.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-patrol-boat.mask.png",
    ),
  },
  {
    id: "chibi-portrait-raider",
    subject: "PORTRAIT:RAIDER",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-raider.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-raider.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-abomination",
    subject: "PORTRAIT:UNDEAD:JUGGERNAUT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-abomination.png",
    ),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-abomination.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-banshee",
    subject: "PORTRAIT:UNDEAD:MARKSMAN",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-banshee.png",
    ),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-banshee.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-ghoul",
    subject: "PORTRAIT:UNDEAD:RAIDER",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-undead-ghoul.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-ghoul.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-lich",
    subject: "PORTRAIT:UNDEAD:CATAPULT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-undead-lich.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-lich.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-necromancer",
    subject: "PORTRAIT:UNDEAD:CAPTAIN",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-necromancer.png",
    ),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-necromancer.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-skeleton",
    subject: "PORTRAIT:UNDEAD:FIGHTER",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-skeleton.png",
    ),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-skeleton.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-vampire",
    subject: "PORTRAIT:UNDEAD:KNIGHT",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-vampire.png",
    ),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-vampire.mask.png",
    ),
  },
  {
    id: "chibi-portrait-undead-zombie",
    subject: "PORTRAIT:UNDEAD:GUARD",
    assetClass: "PORTRAIT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/portraits/chibi-portrait-undead-zombie.png"),
    ownerMaskUrl: chibiArtUrl(
      "assets/chibi/portraits/chibi-portrait-undead-zombie.mask.png",
    ),
  },
  {
    id: "chibi-icon-action-blast-mountain",
    subject: "ICON:ACTION:BLAST_MOUNTAIN",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-blast-mountain.png"),
  },
  {
    id: "chibi-icon-action-build-road",
    subject: "ICON:ACTION:BUILD_ROAD",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-build-road.png"),
  },
  {
    id: "chibi-icon-action-clear-forest",
    subject: "ICON:ACTION:CLEAR_FOREST",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-clear-forest.png"),
  },
  {
    id: "chibi-icon-action-cultivate-forest",
    subject: "ICON:ACTION:CULTIVATE_FOREST",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl(
      "assets/chibi/icons/chibi-icon-action-cultivate-forest.png",
    ),
  },
  {
    id: "chibi-icon-action-disband",
    subject: "ICON:ACTION:DISBAND",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-disband.png"),
  },
  {
    id: "chibi-icon-action-pillage",
    subject: "ICON:ACTION:PILLAGE",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-pillage.png"),
  },
  {
    id: "chibi-icon-action-promote",
    subject: "ICON:ACTION:PROMOTE",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-promote.png"),
  },
  {
    id: "chibi-icon-action-rally",
    subject: "ICON:ACTION:RALLY",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-rally.png"),
  },
  {
    id: "chibi-icon-action-recover",
    subject: "ICON:ACTION:RECOVER",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-recover.png"),
  },
  {
    id: "chibi-icon-action-redevelop",
    subject: "ICON:ACTION:REDEVELOP",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-redevelop.png"),
  },
  {
    id: "chibi-icon-action-replant-forest",
    subject: "ICON:ACTION:REPLANT_FOREST",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-replant-forest.png"),
  },
  {
    id: "chibi-icon-action-tend-wounded",
    subject: "ICON:ACTION:TEND_WOUNDED",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-tend-wounded.png"),
  },
  {
    id: "chibi-icon-action-wait",
    subject: "ICON:ACTION:WAIT",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-wait.png"),
  },
  {
    id: "chibi-icon-hud-coin",
    subject: "ICON:HUD:COIN",
    assetClass: "ICON",
    width: 32,
    height: 32,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-hud-coin.png"),
  },
  {
    id: "chibi-icon-hud-population",
    subject: "ICON:HUD:POPULATION",
    assetClass: "ICON",
    width: 32,
    height: 32,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-hud-population.png"),
  },
  {
    id: "chibi-icon-reward-expand",
    subject: "ICON:REWARD:EXPAND",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-reward-expand.png"),
  },
  {
    id: "chibi-icon-reward-survey",
    subject: "ICON:REWARD:SURVEY",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-reward-survey.png"),
  },
  {
    id: "chibi-icon-reward-walls",
    subject: "ICON:REWARD:WALLS",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-reward-walls.png"),
  },
  {
    id: "chibi-icon-tech-fieldcraft",
    subject: "ICON:TECH:FIELDCRAFT",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-tech-fieldcraft.png"),
  },
  {
    id: "chibi-icon-tech-fortification",
    subject: "ICON:TECH:FORTIFICATION",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-tech-fortification.png"),
  },
  {
    id: "chibi-icon-tech-navigation",
    subject: "ICON:TECH:NAVIGATION",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-tech-navigation.png"),
  },
  {
    id: "chibi-icon-action-devour",
    subject: "ICON:ACTION:DEVOUR",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-devour.png"),
  },
  {
    id: "chibi-icon-action-raise-dead",
    subject: "ICON:ACTION:RAISE_DEAD",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-raise-dead.png"),
  },
  {
    id: "chibi-icon-action-undead-rally",
    subject: "ICON:ACTION:UNDEAD:RALLY",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-undead-rally.png"),
  },
  {
    id: "chibi-icon-action-wail",
    subject: "ICON:ACTION:WAIL",
    assetClass: "ICON",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/icons/chibi-icon-action-wail.png"),
  },
  // Bead pulp_wars-vkq.14 (batch effects-undead): the revision 14 Plague
  // and Bitten markers and the Undead ability effect sprites.
  {
    id: "chibi-marker-plagued",
    subject: "STATUS:PLAGUED",
    assetClass: "STATUS",
    width: 32,
    height: 32,
    url: chibiArtUrl("assets/chibi/status/chibi-marker-plagued.png"),
  },
  {
    id: "chibi-marker-bitten",
    subject: "STATUS:BITTEN",
    assetClass: "STATUS",
    width: 32,
    height: 32,
    url: chibiArtUrl("assets/chibi/status/chibi-marker-bitten.png"),
  },
  {
    id: "chibi-effect-wail",
    subject: "EFFECT:WAIL",
    assetClass: "EFFECT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/effects/chibi-effect-wail.png"),
  },
  {
    id: "chibi-effect-splash",
    subject: "EFFECT:SPLASH",
    assetClass: "EFFECT",
    width: 48,
    height: 48,
    url: chibiArtUrl("assets/chibi/effects/chibi-effect-splash.png"),
  },
  {
    id: "chibi-effect-raise",
    subject: "EFFECT:RAISE",
    assetClass: "EFFECT",
    width: 40,
    height: 40,
    url: chibiArtUrl("assets/chibi/effects/chibi-effect-raise.png"),
  },
  {
    id: "chibi-effect-wisp",
    subject: "EFFECT:WISP",
    assetClass: "EFFECT",
    width: 24,
    height: 24,
    url: chibiArtUrl("assets/chibi/effects/chibi-effect-wisp.png"),
  },
  {
    id: "chibi-effect-cure",
    subject: "EFFECT:CURE",
    assetClass: "EFFECT",
    width: 32,
    height: 32,
    url: chibiArtUrl("assets/chibi/effects/chibi-effect-cure.png"),
  },
];

export function chibiArtUrl(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}
