// Generated by scripts/art/pixellab.ts. Do not edit by hand.
/// <reference types="vite/client" />

function publicArtUrl(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}

export const ACCEPTED_ART_URLS: Readonly<Record<string, string>> = {
  "unit-warrior": publicArtUrl("assets/pixellab/units/warrior.png"),
  "unit-defender": publicArtUrl("assets/pixellab/units/defender.png"),
  "unit-archer": publicArtUrl("assets/pixellab/units/archer.png"),
  "unit-rider": publicArtUrl("assets/pixellab/units/rider.png"),
  "unit-catapult": publicArtUrl("assets/pixellab/units/catapult.png"),
  "unit-candy-warrior": publicArtUrl("assets/pixellab/units/candy-warrior.png"),
  "unit-candy-gumball-guard": publicArtUrl(
    "assets/pixellab/units/candy-gumball-guard.png",
  ),
  "unit-candy-donut": publicArtUrl("assets/pixellab/units/candy-donut.png"),
  "unit-candy-choco-engineer": publicArtUrl(
    "assets/pixellab/units/candy-choco-engineer.png",
  ),
  "terrain-grass-1": publicArtUrl("assets/pixellab/terrain/grass-1.png"),
  "terrain-grass-2": publicArtUrl("assets/pixellab/terrain/grass-2.png"),
  "terrain-grass-3": publicArtUrl("assets/pixellab/terrain/grass-3.png"),
  "terrain-grass-4": publicArtUrl("assets/pixellab/terrain/grass-4.png"),
  "terrain-mountain-1": publicArtUrl("assets/pixellab/terrain/mountain-1.png"),
  "terrain-mountain-2": publicArtUrl("assets/pixellab/terrain/mountain-2.png"),
  "terrain-mountain-3": publicArtUrl("assets/pixellab/terrain/mountain-3.png"),
  "terrain-ore": publicArtUrl("assets/pixellab/terrain/ore.png"),
  "terrain-fruit": publicArtUrl("assets/pixellab/terrain/fruit.png"),
  "terrain-forest-1": publicArtUrl("assets/pixellab/terrain/forest-1.png"),
  "terrain-forest-2": publicArtUrl("assets/pixellab/terrain/forest-2.png"),
  "terrain-forest-3": publicArtUrl("assets/pixellab/terrain/forest-3.png"),
  "terrain-forest-4": publicArtUrl("assets/pixellab/terrain/forest-4.png"),
  "terrain-animal": publicArtUrl("assets/pixellab/terrain/animal.png"),
  "terrain-fertile-ground": publicArtUrl(
    "assets/pixellab/terrain/fertile-ground.png",
  ),
  "terrain-stone": publicArtUrl("assets/pixellab/terrain/stone.png"),
  "terrain-road-material": publicArtUrl(
    "assets/pixellab/terrain/road-material.png",
  ),
  "terrain-candy-grass-1": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-1.png",
  ),
  "terrain-candy-grass-2": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-2.png",
  ),
  "terrain-candy-grass-3": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-3.png",
  ),
  "terrain-candy-grass-4": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-4.png",
  ),
  "terrain-candy-mountain-1": publicArtUrl(
    "assets/pixellab/terrain/candy-mountain-1.png",
  ),
  "terrain-candy-mountain-2": publicArtUrl(
    "assets/pixellab/terrain/candy-mountain-2.png",
  ),
  "terrain-candy-mountain-3": publicArtUrl(
    "assets/pixellab/terrain/candy-mountain-3.png",
  ),
  "terrain-candy-forest-1": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-1.png",
  ),
  "terrain-candy-forest-2": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-2.png",
  ),
  "terrain-candy-forest-3": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-3.png",
  ),
  "terrain-candy-forest-4": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-4.png",
  ),
  "terrain-candy-fruit": publicArtUrl(
    "assets/pixellab/terrain/candy-fruit.png",
  ),
  "terrain-candy-animal": publicArtUrl(
    "assets/pixellab/terrain/candy-animal.png",
  ),
  "building-farm": publicArtUrl("assets/pixellab/buildings/farm.png"),
  "building-quarry": publicArtUrl("assets/pixellab/buildings/quarry.png"),
  "building-windmill": publicArtUrl("assets/pixellab/buildings/windmill.png"),
  "building-sawmill": publicArtUrl("assets/pixellab/buildings/sawmill.png"),
  "building-forge": publicArtUrl("assets/pixellab/buildings/forge.png"),
  "building-stoneworks": publicArtUrl(
    "assets/pixellab/buildings/stoneworks.png",
  ),
  "building-workshop": publicArtUrl("assets/pixellab/buildings/workshop.png"),
  "building-grand-works": publicArtUrl(
    "assets/pixellab/buildings/grand-works.png",
  ),
  "building-market": publicArtUrl("assets/pixellab/buildings/market.png"),
  "building-village": publicArtUrl("assets/pixellab/buildings/village.png"),
  "building-city-1": publicArtUrl("assets/pixellab/buildings/city-1.png"),
  "building-city-3": publicArtUrl("assets/pixellab/buildings/city-3.png"),
  "building-city-2": publicArtUrl("assets/pixellab/buildings/city-2.png"),
  "building-candy-city-1": publicArtUrl(
    "assets/pixellab/buildings/candy-city-1.png",
  ),
  "building-candy-city-2": publicArtUrl(
    "assets/pixellab/buildings/candy-city-2.png",
  ),
  "building-candy-city-3": publicArtUrl(
    "assets/pixellab/buildings/candy-city-3.png",
  ),
  "building-mine": publicArtUrl("assets/pixellab/buildings/mine.png"),
  "building-lumber-mill": publicArtUrl(
    "assets/pixellab/buildings/lumber-mill.png",
  ),
  "building-chocolate-wall": publicArtUrl(
    "assets/pixellab/buildings/chocolate-wall.png",
  ),
  "ui-star": publicArtUrl("assets/pixellab/ui/star.png"),
  "ui-attack": publicArtUrl("assets/pixellab/ui/attack.png"),
  "ui-tech-climbing": publicArtUrl("assets/pixellab/ui/tech-climbing.png"),
  "ui-tech-riding": publicArtUrl("assets/pixellab/ui/tech-riding.png"),
  "ui-tech-hunting": publicArtUrl("assets/pixellab/ui/tech-hunting.png"),
  "ui-tech-organization": publicArtUrl(
    "assets/pixellab/ui/tech-organization.png",
  ),
  "ui-tech-mining": publicArtUrl("assets/pixellab/ui/tech-mining.png"),
  "ui-tech-archery": publicArtUrl("assets/pixellab/ui/tech-archery.png"),
  "ui-tech-strategy": publicArtUrl("assets/pixellab/ui/tech-strategy.png"),
  "ui-tech-forestry": publicArtUrl("assets/pixellab/ui/tech-forestry.png"),
  "ui-tech-mathematics": publicArtUrl(
    "assets/pixellab/ui/tech-mathematics.png",
  ),
  "ui-reward-workshop": publicArtUrl("assets/pixellab/ui/reward-workshop.png"),
  "ui-reward-survey": publicArtUrl("assets/pixellab/ui/reward-survey.png"),
  "ui-reward-resources": publicArtUrl(
    "assets/pixellab/ui/reward-resources.png",
  ),
  "ui-reward-city-wall": publicArtUrl(
    "assets/pixellab/ui/reward-city-wall.png",
  ),
  "ui-faction-candy-badge": publicArtUrl(
    "assets/pixellab/ui/faction-candy-badge.png",
  ),
  "ui-action-kamikaze-roll": publicArtUrl(
    "assets/pixellab/ui/action-kamikaze-roll.png",
  ),
  "ui-action-candify": publicArtUrl("assets/pixellab/ui/action-candify.png"),
  "ui-action-build-chocolate-wall": publicArtUrl(
    "assets/pixellab/ui/action-build-chocolate-wall.png",
  ),
  "ui-action-choose-candify-city": publicArtUrl(
    "assets/pixellab/ui/action-choose-candify-city.png",
  ),
  "ui-faction-candy-hero": publicArtUrl(
    "assets/pixellab/ui/faction-candy-hero.png",
  ),
  "ui-faction-hero": publicArtUrl("assets/pixellab/ui/faction-hero.png"),
  "terrain-game": publicArtUrl("assets/pixellab/terrain/animal.png"),
  "building-ruleset6-mine": publicArtUrl("assets/pixellab/buildings/mine.png"),
  "building-lumber-camp": publicArtUrl(
    "assets/pixellab/buildings/lumber-mill.png",
  ),
  "terrain-road-mask-0000": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0000.png",
  ),
  "terrain-road-mask-0001": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0001.png",
  ),
  "terrain-road-mask-0010": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0010.png",
  ),
  "terrain-road-mask-0011": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0011.png",
  ),
  "terrain-road-mask-0100": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0100.png",
  ),
  "terrain-road-mask-0101": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0101.png",
  ),
  "terrain-road-mask-0110": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0110.png",
  ),
  "terrain-road-mask-0111": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0111.png",
  ),
  "terrain-road-mask-1000": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1000.png",
  ),
  "terrain-road-mask-1001": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1001.png",
  ),
  "terrain-road-mask-1010": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1010.png",
  ),
  "terrain-road-mask-1011": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1011.png",
  ),
  "terrain-road-mask-1100": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1100.png",
  ),
  "terrain-road-mask-1101": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1101.png",
  ),
  "terrain-road-mask-1110": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1110.png",
  ),
  "terrain-road-mask-1111": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1111.png",
  ),
};

export const ACCEPTED_ART_ALIASES: Readonly<Record<string, string>> = {
  "terrain-game": "terrain-animal",
  "building-ruleset6-mine": "building-mine",
  "building-lumber-camp": "building-lumber-mill",
};

export interface AcceptedArtAttachment {
  readonly projectileOrigin?: { readonly x: number; readonly y: number };
}

export const ACCEPTED_ART_ATTACHMENTS: Readonly<
  Record<string, AcceptedArtAttachment>
> = {
  "unit-archer": { projectileOrigin: { x: 0.7, y: 0.37 } },
  "unit-candy-gumball-guard": { projectileOrigin: { x: 0.6523, y: 0.5156 } },
};

export const FACTION_HERO_URL = ACCEPTED_ART_URLS["ui-faction-hero"] ?? null;
export const FACTION_HERO_URLS = Object.freeze({
  ORIGINAL: ACCEPTED_ART_URLS["ui-faction-hero"] ?? null,
  CANDY: ACCEPTED_ART_URLS["ui-faction-candy-hero"] ?? null,
});
export const FACTION_BADGE_URLS = Object.freeze({
  ORIGINAL: null,
  CANDY: ACCEPTED_ART_URLS["ui-faction-candy-badge"] ?? null,
});
export const CANDY_ACTION_ART_URLS = Object.freeze({
  KAMIKAZE_ROLL: ACCEPTED_ART_URLS["ui-action-kamikaze-roll"] ?? null,
  BUILD_CHOCOLATE_WALL:
    ACCEPTED_ART_URLS["ui-action-build-chocolate-wall"] ?? null,
  CANDIFY: ACCEPTED_ART_URLS["ui-action-candify"] ?? null,
  CHOOSE_CANDIFY_CITY:
    ACCEPTED_ART_URLS["ui-action-choose-candify-city"] ?? null,
});
