// Generated by scripts/art/pixellab.ts. Do not edit by hand.
/// <reference types="vite/client" />

function publicArtUrl(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}

export const ACCEPTED_ART_URLS: Readonly<Record<string, string>> = {
  "unit-warrior": publicArtUrl("assets/pixellab/units/warrior.png"),
  "unit-defender": publicArtUrl("assets/pixellab/units/defender.png"),
  "unit-archer": publicArtUrl("assets/pixellab/units/archer.png"),
  "unit-rider": publicArtUrl("assets/pixellab/units/rider.png"),
  "unit-catapult": publicArtUrl("assets/pixellab/units/catapult.png"),
  "unit-candy-warrior": publicArtUrl("assets/pixellab/units/candy-warrior.png"),
  "unit-candy-gumball-guard": publicArtUrl(
    "assets/pixellab/units/candy-gumball-guard.png",
  ),
  "unit-candy-donut": publicArtUrl("assets/pixellab/units/candy-donut.png"),
  "unit-candy-choco-engineer": publicArtUrl(
    "assets/pixellab/units/candy-choco-engineer.png",
  ),
  "unit-original-scout": publicArtUrl(
    "assets/pixellab/units/original-scout.png",
  ),
  "unit-original-medic": publicArtUrl(
    "assets/pixellab/units/original-medic.png",
  ),
  "unit-original-breacher": publicArtUrl(
    "assets/pixellab/units/original-breacher.png",
  ),
  "unit-original-heavy": publicArtUrl(
    "assets/pixellab/units/original-heavy.png",
  ),
  "unit-original-juggernaut": publicArtUrl(
    "assets/pixellab/units/original-juggernaut.png",
  ),
  "portrait-original-fighter": publicArtUrl(
    "assets/pixellab/ui/portrait-original-fighter.png",
  ),
  "portrait-original-scout": publicArtUrl(
    "assets/pixellab/ui/portrait-original-scout.png",
  ),
  "portrait-original-marksman": publicArtUrl(
    "assets/pixellab/ui/portrait-original-marksman.png",
  ),
  "portrait-original-guard": publicArtUrl(
    "assets/pixellab/ui/portrait-original-guard.png",
  ),
  "portrait-original-raider": publicArtUrl(
    "assets/pixellab/ui/portrait-original-raider.png",
  ),
  "portrait-original-medic": publicArtUrl(
    "assets/pixellab/ui/portrait-original-medic.png",
  ),
  "portrait-original-heavy": publicArtUrl(
    "assets/pixellab/ui/portrait-original-heavy.png",
  ),
  "portrait-original-breacher": publicArtUrl(
    "assets/pixellab/ui/portrait-original-breacher.png",
  ),
  "portrait-original-juggernaut": publicArtUrl(
    "assets/pixellab/ui/portrait-original-juggernaut.png",
  ),
  "unit-candy-scout": publicArtUrl(
    "assets/pixellab/units/candy-jelly-scout.png",
  ),
  "unit-candy-medic": publicArtUrl(
    "assets/pixellab/units/candy-marshmallow-medic.png",
  ),
  "unit-candy-breacher": publicArtUrl(
    "assets/pixellab/units/candy-crusher.png",
  ),
  "unit-candy-heavy": publicArtUrl(
    "assets/pixellab/units/candy-jawbreaker.png",
  ),
  "unit-candy-juggernaut": publicArtUrl(
    "assets/pixellab/units/candy-sugar-titan.png",
  ),
  "portrait-candy-fighter": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-fighter.png",
  ),
  "portrait-candy-scout": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-scout.png",
  ),
  "portrait-candy-marksman": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-marksman.png",
  ),
  "portrait-candy-guard": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-guard.png",
  ),
  "portrait-candy-raider": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-raider.png",
  ),
  "portrait-candy-medic": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-medic.png",
  ),
  "portrait-candy-heavy": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-heavy.png",
  ),
  "portrait-candy-breacher": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-breacher.png",
  ),
  "portrait-candy-juggernaut": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-juggernaut.png",
  ),
  "terrain-grass-1": publicArtUrl("assets/pixellab/terrain/grass-1.png"),
  "terrain-grass-2": publicArtUrl("assets/pixellab/terrain/grass-2.png"),
  "terrain-grass-3": publicArtUrl("assets/pixellab/terrain/grass-3.png"),
  "terrain-grass-4": publicArtUrl("assets/pixellab/terrain/grass-4.png"),
  "terrain-mountain-1": publicArtUrl("assets/pixellab/terrain/mountain-1.png"),
  "terrain-mountain-2": publicArtUrl("assets/pixellab/terrain/mountain-2.png"),
  "terrain-mountain-3": publicArtUrl("assets/pixellab/terrain/mountain-3.png"),
  "terrain-ore": publicArtUrl("assets/pixellab/terrain/ore.png"),
  "terrain-fruit": publicArtUrl("assets/pixellab/terrain/fruit.png"),
  "terrain-forest-1": publicArtUrl("assets/pixellab/terrain/forest-1.png"),
  "terrain-forest-2": publicArtUrl("assets/pixellab/terrain/forest-2.png"),
  "terrain-forest-3": publicArtUrl("assets/pixellab/terrain/forest-3.png"),
  "terrain-forest-4": publicArtUrl("assets/pixellab/terrain/forest-4.png"),
  "terrain-animal": publicArtUrl("assets/pixellab/terrain/animal.png"),
  "terrain-fertile-ground": publicArtUrl(
    "assets/pixellab/terrain/fertile-ground.png",
  ),
  "terrain-stone": publicArtUrl("assets/pixellab/terrain/stone.png"),
  "terrain-road-material": publicArtUrl(
    "assets/pixellab/terrain/road-material.png",
  ),
  "terrain-candy-grass-1": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-1.png",
  ),
  "terrain-candy-grass-2": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-2.png",
  ),
  "terrain-candy-grass-3": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-3.png",
  ),
  "terrain-candy-grass-4": publicArtUrl(
    "assets/pixellab/terrain/candy-grass-4.png",
  ),
  "terrain-candy-mountain-1": publicArtUrl(
    "assets/pixellab/terrain/candy-mountain-1.png",
  ),
  "terrain-candy-mountain-2": publicArtUrl(
    "assets/pixellab/terrain/candy-mountain-2.png",
  ),
  "terrain-candy-mountain-3": publicArtUrl(
    "assets/pixellab/terrain/candy-mountain-3.png",
  ),
  "terrain-candy-forest-1": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-1.png",
  ),
  "terrain-candy-forest-2": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-2.png",
  ),
  "terrain-candy-forest-3": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-3.png",
  ),
  "terrain-candy-forest-4": publicArtUrl(
    "assets/pixellab/terrain/candy-forest-4.png",
  ),
  "terrain-candy-fruit": publicArtUrl(
    "assets/pixellab/terrain/candy-fruit.png",
  ),
  "terrain-candy-animal": publicArtUrl(
    "assets/pixellab/terrain/candy-animal.png",
  ),
  "building-farm": publicArtUrl("assets/pixellab/buildings/farm.png"),
  "building-quarry": publicArtUrl("assets/pixellab/buildings/quarry.png"),
  "building-windmill": publicArtUrl("assets/pixellab/buildings/windmill.png"),
  "building-sawmill": publicArtUrl("assets/pixellab/buildings/sawmill.png"),
  "building-forge": publicArtUrl("assets/pixellab/buildings/forge.png"),
  "building-stoneworks": publicArtUrl(
    "assets/pixellab/buildings/stoneworks.png",
  ),
  "building-workshop": publicArtUrl("assets/pixellab/buildings/workshop.png"),
  "building-grand-works": publicArtUrl(
    "assets/pixellab/buildings/grand-works.png",
  ),
  "building-market": publicArtUrl("assets/pixellab/buildings/market.png"),
  "building-village": publicArtUrl("assets/pixellab/buildings/village.png"),
  "building-city-1": publicArtUrl("assets/pixellab/buildings/city-1.png"),
  "building-city-3": publicArtUrl("assets/pixellab/buildings/city-3.png"),
  "building-city-2": publicArtUrl("assets/pixellab/buildings/city-2.png"),
  "building-candy-city-1": publicArtUrl(
    "assets/pixellab/buildings/candy-city-1.png",
  ),
  "building-candy-city-2": publicArtUrl(
    "assets/pixellab/buildings/candy-city-2.png",
  ),
  "building-candy-city-3": publicArtUrl(
    "assets/pixellab/buildings/candy-city-3.png",
  ),
  "building-mine": publicArtUrl("assets/pixellab/buildings/mine.png"),
  "building-lumber-mill": publicArtUrl(
    "assets/pixellab/buildings/lumber-mill.png",
  ),
  "building-chocolate-wall": publicArtUrl(
    "assets/pixellab/buildings/chocolate-wall.png",
  ),
  "ui-star": publicArtUrl("assets/pixellab/ui/star.png"),
  "ui-attack": publicArtUrl("assets/pixellab/ui/attack.png"),
  "ui-tech-climbing": publicArtUrl("assets/pixellab/ui/tech-climbing.png"),
  "ui-tech-riding": publicArtUrl("assets/pixellab/ui/tech-riding.png"),
  "ui-tech-hunting": publicArtUrl("assets/pixellab/ui/tech-hunting.png"),
  "ui-tech-organization": publicArtUrl(
    "assets/pixellab/ui/tech-organization.png",
  ),
  "ui-tech-mining": publicArtUrl("assets/pixellab/ui/tech-mining.png"),
  "ui-tech-archery": publicArtUrl("assets/pixellab/ui/tech-archery.png"),
  "ui-tech-strategy": publicArtUrl("assets/pixellab/ui/tech-strategy.png"),
  "ui-tech-forestry": publicArtUrl("assets/pixellab/ui/tech-forestry.png"),
  "ui-tech-mathematics": publicArtUrl(
    "assets/pixellab/ui/tech-mathematics.png",
  ),
  "ui-reward-workshop": publicArtUrl("assets/pixellab/ui/reward-workshop.png"),
  "ui-reward-survey": publicArtUrl("assets/pixellab/ui/reward-survey.png"),
  "ui-reward-resources": publicArtUrl(
    "assets/pixellab/ui/reward-resources.png",
  ),
  "ui-reward-city-wall": publicArtUrl(
    "assets/pixellab/ui/reward-city-wall.png",
  ),
  "ui-faction-candy-badge": publicArtUrl(
    "assets/pixellab/ui/faction-candy-badge.png",
  ),
  "ui-action-kamikaze-roll": publicArtUrl(
    "assets/pixellab/ui/action-kamikaze-roll.png",
  ),
  "ui-action-candify": publicArtUrl("assets/pixellab/ui/action-candify.png"),
  "ui-action-build-chocolate-wall": publicArtUrl(
    "assets/pixellab/ui/action-build-chocolate-wall.png",
  ),
  "ui-action-choose-candify-city": publicArtUrl(
    "assets/pixellab/ui/action-choose-candify-city.png",
  ),
  "ui-faction-candy-hero": publicArtUrl(
    "assets/pixellab/ui/faction-candy-hero.png",
  ),
  "ui-faction-hero": publicArtUrl("assets/pixellab/ui/faction-hero.png"),
  "ui-hud-coin": publicArtUrl("assets/pixellab/ui/hud-coin.png"),
  "ui-action-redevelop": publicArtUrl(
    "assets/pixellab/ui/action-redevelop.png",
  ),
  "ui-tech-fieldcraft": publicArtUrl("assets/pixellab/ui/tech-fieldcraft.png"),
  "ui-hud-population": publicArtUrl("assets/pixellab/ui/hud-population.png"),
  "ui-hud-negative-population": publicArtUrl(
    "assets/pixellab/ui/hud-negative-population.png",
  ),
  "ui-hud-capacity": publicArtUrl("assets/pixellab/ui/hud-capacity.png"),
  "ui-action-clear-forest": publicArtUrl(
    "assets/pixellab/ui/action-clear-forest.png",
  ),
  "ui-action-replant-forest": publicArtUrl(
    "assets/pixellab/ui/action-replant-forest.png",
  ),
  "ui-reward-expand": publicArtUrl("assets/pixellab/ui/reward-expand.png"),
  "ui-action-heal": publicArtUrl("assets/pixellab/ui/action-heal.png"),
  "ui-action-recover": publicArtUrl("assets/pixellab/ui/action-recover.png"),
  "ui-action-wait": publicArtUrl("assets/pixellab/ui/action-wait.png"),
  "ui-action-promote": publicArtUrl("assets/pixellab/ui/action-promote.png"),
  "ui-action-end-turn": publicArtUrl("assets/pixellab/ui/action-end-turn.png"),
  "ui-tech-maneuver": publicArtUrl("assets/pixellab/ui/tech-maneuver.png"),
  "ui-tech-fortification": publicArtUrl(
    "assets/pixellab/ui/tech-fortification.png",
  ),
  "ui-tech-recovery": publicArtUrl("assets/pixellab/ui/tech-recovery.png"),
  "terrain-square-original-grass-1": publicArtUrl(
    "assets/pixellab/terrain-square/original-grass-1.png",
  ),
  "terrain-square-original-forest-1": publicArtUrl(
    "assets/pixellab/terrain-square/original-forest-1.png",
  ),
  "terrain-square-original-mountain-1": publicArtUrl(
    "assets/pixellab/terrain-square/original-mountain-1.png",
  ),
  "terrain-square-original-grass-2": publicArtUrl(
    "assets/pixellab/terrain-square/original-grass-2.png",
  ),
  "terrain-square-original-grass-3": publicArtUrl(
    "assets/pixellab/terrain-square/original-grass-3.png",
  ),
  "terrain-square-original-grass-4": publicArtUrl(
    "assets/pixellab/terrain-square/original-grass-4.png",
  ),
  "terrain-square-original-forest-2": publicArtUrl(
    "assets/pixellab/terrain-square/original-forest-2.png",
  ),
  "terrain-square-original-forest-3": publicArtUrl(
    "assets/pixellab/terrain-square/original-forest-3.png",
  ),
  "terrain-square-original-forest-4": publicArtUrl(
    "assets/pixellab/terrain-square/original-forest-4.png",
  ),
  "terrain-square-original-mountain-2": publicArtUrl(
    "assets/pixellab/terrain-square/original-mountain-2.png",
  ),
  "terrain-square-original-mountain-3": publicArtUrl(
    "assets/pixellab/terrain-square/original-mountain-3.png",
  ),
  "terrain-square-candy-grass-1": publicArtUrl(
    "assets/pixellab/terrain-square/candy-grass-1.png",
  ),
  "terrain-square-candy-forest-1": publicArtUrl(
    "assets/pixellab/terrain-square/candy-forest-1.png",
  ),
  "terrain-square-candy-mountain-1": publicArtUrl(
    "assets/pixellab/terrain-square/candy-mountain-1.png",
  ),
  "terrain-square-candy-grass-2": publicArtUrl(
    "assets/pixellab/terrain-square/candy-grass-2.png",
  ),
  "terrain-square-candy-grass-3": publicArtUrl(
    "assets/pixellab/terrain-square/candy-grass-3.png",
  ),
  "terrain-square-candy-grass-4": publicArtUrl(
    "assets/pixellab/terrain-square/candy-grass-4.png",
  ),
  "terrain-square-candy-forest-2": publicArtUrl(
    "assets/pixellab/terrain-square/candy-forest-2.png",
  ),
  "terrain-square-candy-forest-3": publicArtUrl(
    "assets/pixellab/terrain-square/candy-forest-3.png",
  ),
  "terrain-square-candy-forest-4": publicArtUrl(
    "assets/pixellab/terrain-square/candy-forest-4.png",
  ),
  "terrain-square-candy-mountain-2": publicArtUrl(
    "assets/pixellab/terrain-square/candy-mountain-2.png",
  ),
  "terrain-square-candy-mountain-3": publicArtUrl(
    "assets/pixellab/terrain-square/candy-mountain-3.png",
  ),
  "terrain-game": publicArtUrl("assets/pixellab/terrain/animal.png"),
  "building-ruleset6-mine": publicArtUrl("assets/pixellab/buildings/mine.png"),
  "building-lumber-camp": publicArtUrl(
    "assets/pixellab/buildings/lumber-mill.png",
  ),
  "unit-original-fighter": publicArtUrl("assets/pixellab/units/warrior.png"),
  "unit-original-marksman": publicArtUrl("assets/pixellab/units/archer.png"),
  "unit-original-guard": publicArtUrl("assets/pixellab/units/defender.png"),
  "unit-original-raider": publicArtUrl("assets/pixellab/units/rider.png"),
  "unit-candy-fighter": publicArtUrl("assets/pixellab/units/candy-warrior.png"),
  "unit-candy-marksman": publicArtUrl(
    "assets/pixellab/units/candy-gumball-guard.png",
  ),
  "unit-candy-guard": publicArtUrl(
    "assets/pixellab/units/candy-choco-engineer.png",
  ),
  "unit-candy-raider": publicArtUrl("assets/pixellab/units/candy-donut.png"),
  "ui-hud-income": publicArtUrl("assets/pixellab/ui/hud-coin.png"),
  "ui-hud-road": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0101.png",
  ),
  "ui-tech-original-gathering": publicArtUrl(
    "assets/pixellab/terrain/fruit.png",
  ),
  "ui-tech-original-farming": publicArtUrl(
    "assets/pixellab/buildings/farm.png",
  ),
  "ui-tech-original-milling": publicArtUrl(
    "assets/pixellab/buildings/windmill.png",
  ),
  "ui-tech-original-craft": publicArtUrl(
    "assets/pixellab/buildings/workshop.png",
  ),
  "ui-tech-original-grand-works": publicArtUrl(
    "assets/pixellab/buildings/grand-works.png",
  ),
  "ui-tech-original-hunting": publicArtUrl(
    "assets/pixellab/terrain/animal.png",
  ),
  "ui-tech-original-forestry": publicArtUrl(
    "assets/pixellab/buildings/lumber-mill.png",
  ),
  "ui-tech-original-sawmilling": publicArtUrl(
    "assets/pixellab/buildings/sawmill.png",
  ),
  "ui-tech-original-marksmanship": publicArtUrl(
    "assets/pixellab/ui/portrait-original-marksman.png",
  ),
  "ui-tech-original-fieldcraft": publicArtUrl(
    "assets/pixellab/ui/tech-fieldcraft.png",
  ),
  "ui-tech-original-surveying": publicArtUrl(
    "assets/pixellab/ui/reward-survey.png",
  ),
  "ui-tech-original-mining": publicArtUrl("assets/pixellab/buildings/mine.png"),
  "ui-tech-original-metallurgy": publicArtUrl(
    "assets/pixellab/buildings/forge.png",
  ),
  "ui-tech-original-quarrying": publicArtUrl(
    "assets/pixellab/buildings/quarry.png",
  ),
  "ui-tech-original-masonry": publicArtUrl(
    "assets/pixellab/buildings/stoneworks.png",
  ),
  "ui-tech-original-scouting": publicArtUrl(
    "assets/pixellab/ui/portrait-original-scout.png",
  ),
  "ui-tech-original-roads": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0101.png",
  ),
  "ui-tech-original-commerce": publicArtUrl(
    "assets/pixellab/buildings/market.png",
  ),
  "ui-tech-original-raiding": publicArtUrl(
    "assets/pixellab/ui/portrait-original-raider.png",
  ),
  "ui-tech-original-maneuver": publicArtUrl(
    "assets/pixellab/ui/tech-maneuver.png",
  ),
  "ui-tech-original-drill": publicArtUrl(
    "assets/pixellab/ui/portrait-original-guard.png",
  ),
  "ui-tech-original-fortification": publicArtUrl(
    "assets/pixellab/ui/tech-fortification.png",
  ),
  "ui-tech-original-explosives": publicArtUrl(
    "assets/pixellab/ui/portrait-original-breacher.png",
  ),
  "ui-tech-original-medicine": publicArtUrl(
    "assets/pixellab/ui/portrait-original-medic.png",
  ),
  "ui-tech-original-recovery": publicArtUrl(
    "assets/pixellab/ui/tech-recovery.png",
  ),
  "ui-tech-candy-gathering": publicArtUrl(
    "assets/pixellab/terrain/candy-fruit.png",
  ),
  "ui-tech-candy-farming": publicArtUrl("assets/pixellab/buildings/farm.png"),
  "ui-tech-candy-milling": publicArtUrl(
    "assets/pixellab/buildings/windmill.png",
  ),
  "ui-tech-candy-craft": publicArtUrl("assets/pixellab/buildings/workshop.png"),
  "ui-tech-candy-grand-works": publicArtUrl(
    "assets/pixellab/buildings/grand-works.png",
  ),
  "ui-tech-candy-hunting": publicArtUrl(
    "assets/pixellab/terrain/candy-animal.png",
  ),
  "ui-tech-candy-forestry": publicArtUrl(
    "assets/pixellab/buildings/lumber-mill.png",
  ),
  "ui-tech-candy-sawmilling": publicArtUrl(
    "assets/pixellab/buildings/sawmill.png",
  ),
  "ui-tech-candy-marksmanship": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-marksman.png",
  ),
  "ui-tech-candy-fieldcraft": publicArtUrl(
    "assets/pixellab/ui/tech-fieldcraft.png",
  ),
  "ui-tech-candy-surveying": publicArtUrl(
    "assets/pixellab/ui/reward-survey.png",
  ),
  "ui-tech-candy-mining": publicArtUrl("assets/pixellab/buildings/mine.png"),
  "ui-tech-candy-metallurgy": publicArtUrl(
    "assets/pixellab/buildings/forge.png",
  ),
  "ui-tech-candy-quarrying": publicArtUrl(
    "assets/pixellab/buildings/quarry.png",
  ),
  "ui-tech-candy-masonry": publicArtUrl(
    "assets/pixellab/buildings/stoneworks.png",
  ),
  "ui-tech-candy-scouting": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-scout.png",
  ),
  "ui-tech-candy-roads": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0101.png",
  ),
  "ui-tech-candy-commerce": publicArtUrl(
    "assets/pixellab/buildings/market.png",
  ),
  "ui-tech-candy-raiding": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-raider.png",
  ),
  "ui-tech-candy-maneuver": publicArtUrl(
    "assets/pixellab/ui/tech-maneuver.png",
  ),
  "ui-tech-candy-drill": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-guard.png",
  ),
  "ui-tech-candy-fortification": publicArtUrl(
    "assets/pixellab/ui/tech-fortification.png",
  ),
  "ui-tech-candy-explosives": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-breacher.png",
  ),
  "ui-tech-candy-medicine": publicArtUrl(
    "assets/pixellab/ui/portrait-candy-medic.png",
  ),
  "ui-tech-candy-recovery": publicArtUrl(
    "assets/pixellab/ui/tech-recovery.png",
  ),
  "terrain-road-mask-0000": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0000.png",
  ),
  "terrain-road-mask-0001": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0001.png",
  ),
  "terrain-road-mask-0010": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0010.png",
  ),
  "terrain-road-mask-0011": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0011.png",
  ),
  "terrain-road-mask-0100": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0100.png",
  ),
  "terrain-road-mask-0101": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0101.png",
  ),
  "terrain-road-mask-0110": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0110.png",
  ),
  "terrain-road-mask-0111": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-0111.png",
  ),
  "terrain-road-mask-1000": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1000.png",
  ),
  "terrain-road-mask-1001": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1001.png",
  ),
  "terrain-road-mask-1010": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1010.png",
  ),
  "terrain-road-mask-1011": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1011.png",
  ),
  "terrain-road-mask-1100": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1100.png",
  ),
  "terrain-road-mask-1101": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1101.png",
  ),
  "terrain-road-mask-1110": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1110.png",
  ),
  "terrain-road-mask-1111": publicArtUrl(
    "assets/pixellab/terrain/road-masks/road-mask-1111.png",
  ),
};

export const ACCEPTED_ART_ALIASES: Readonly<Record<string, string>> = {
  "terrain-game": "terrain-animal",
  "building-ruleset6-mine": "building-mine",
  "building-lumber-camp": "building-lumber-mill",
  "unit-original-fighter": "unit-warrior",
  "unit-original-marksman": "unit-archer",
  "unit-original-guard": "unit-defender",
  "unit-original-raider": "unit-rider",
  "unit-candy-fighter": "unit-candy-warrior",
  "unit-candy-marksman": "unit-candy-gumball-guard",
  "unit-candy-guard": "unit-candy-choco-engineer",
  "unit-candy-raider": "unit-candy-donut",
  "ui-hud-income": "ui-hud-coin",
  "ui-hud-road": "terrain-road-mask-0101",
  "ui-tech-original-gathering": "terrain-fruit",
  "ui-tech-original-farming": "building-farm",
  "ui-tech-original-milling": "building-windmill",
  "ui-tech-original-craft": "building-workshop",
  "ui-tech-original-grand-works": "building-grand-works",
  "ui-tech-original-hunting": "terrain-animal",
  "ui-tech-original-forestry": "building-lumber-mill",
  "ui-tech-original-sawmilling": "building-sawmill",
  "ui-tech-original-marksmanship": "portrait-original-marksman",
  "ui-tech-original-fieldcraft": "ui-tech-fieldcraft",
  "ui-tech-original-surveying": "ui-reward-survey",
  "ui-tech-original-mining": "building-mine",
  "ui-tech-original-metallurgy": "building-forge",
  "ui-tech-original-quarrying": "building-quarry",
  "ui-tech-original-masonry": "building-stoneworks",
  "ui-tech-original-scouting": "portrait-original-scout",
  "ui-tech-original-roads": "terrain-road-mask-0101",
  "ui-tech-original-commerce": "building-market",
  "ui-tech-original-raiding": "portrait-original-raider",
  "ui-tech-original-maneuver": "ui-tech-maneuver",
  "ui-tech-original-drill": "portrait-original-guard",
  "ui-tech-original-fortification": "ui-tech-fortification",
  "ui-tech-original-explosives": "portrait-original-breacher",
  "ui-tech-original-medicine": "portrait-original-medic",
  "ui-tech-original-recovery": "ui-tech-recovery",
  "ui-tech-candy-gathering": "terrain-candy-fruit",
  "ui-tech-candy-farming": "building-farm",
  "ui-tech-candy-milling": "building-windmill",
  "ui-tech-candy-craft": "building-workshop",
  "ui-tech-candy-grand-works": "building-grand-works",
  "ui-tech-candy-hunting": "terrain-candy-animal",
  "ui-tech-candy-forestry": "building-lumber-mill",
  "ui-tech-candy-sawmilling": "building-sawmill",
  "ui-tech-candy-marksmanship": "portrait-candy-marksman",
  "ui-tech-candy-fieldcraft": "ui-tech-fieldcraft",
  "ui-tech-candy-surveying": "ui-reward-survey",
  "ui-tech-candy-mining": "building-mine",
  "ui-tech-candy-metallurgy": "building-forge",
  "ui-tech-candy-quarrying": "building-quarry",
  "ui-tech-candy-masonry": "building-stoneworks",
  "ui-tech-candy-scouting": "portrait-candy-scout",
  "ui-tech-candy-roads": "terrain-road-mask-0101",
  "ui-tech-candy-commerce": "building-market",
  "ui-tech-candy-raiding": "portrait-candy-raider",
  "ui-tech-candy-maneuver": "ui-tech-maneuver",
  "ui-tech-candy-drill": "portrait-candy-guard",
  "ui-tech-candy-fortification": "ui-tech-fortification",
  "ui-tech-candy-explosives": "portrait-candy-breacher",
  "ui-tech-candy-medicine": "portrait-candy-medic",
  "ui-tech-candy-recovery": "ui-tech-recovery",
};

export interface AcceptedArtAttachment {
  readonly projectileOrigin?: { readonly x: number; readonly y: number };
}

export const ACCEPTED_ART_ATTACHMENTS: Readonly<
  Record<string, AcceptedArtAttachment>
> = {
  "unit-archer": { projectileOrigin: { x: 0.7, y: 0.37 } },
  "unit-candy-gumball-guard": { projectileOrigin: { x: 0.6523, y: 0.5156 } },
};

export const FACTION_HERO_URL = ACCEPTED_ART_URLS["ui-faction-hero"] ?? null;
export const FACTION_HERO_URLS = Object.freeze({
  ORIGINAL: ACCEPTED_ART_URLS["ui-faction-hero"] ?? null,
  CANDY: ACCEPTED_ART_URLS["ui-faction-candy-hero"] ?? null,
});
export const FACTION_BADGE_URLS = Object.freeze({
  ORIGINAL: null,
  CANDY: ACCEPTED_ART_URLS["ui-faction-candy-badge"] ?? null,
});
export const CANDY_ACTION_ART_URLS = Object.freeze({
  KAMIKAZE_ROLL: ACCEPTED_ART_URLS["ui-action-kamikaze-roll"] ?? null,
  BUILD_CHOCOLATE_WALL:
    ACCEPTED_ART_URLS["ui-action-build-chocolate-wall"] ?? null,
  CANDIFY: ACCEPTED_ART_URLS["ui-action-candify"] ?? null,
  CHOOSE_CANDIFY_CITY:
    ACCEPTED_ART_URLS["ui-action-choose-candify-city"] ?? null,
});
