// Generated by scripts/art/pixellab.ts. Do not edit by hand.
export const ACCEPTED_ART_URLS: Readonly<Record<string, string>> = {
  "unit-warrior": "/assets/pixellab/units/warrior.png",
  "unit-defender": "/assets/pixellab/units/defender.png",
  "unit-archer": "/assets/pixellab/units/archer.png",
  "unit-rider": "/assets/pixellab/units/rider.png",
  "unit-catapult": "/assets/pixellab/units/catapult.png",
  "unit-candy-warrior": "/assets/pixellab/units/candy-warrior.png",
  "unit-candy-gumball-guard": "/assets/pixellab/units/candy-gumball-guard.png",
  "unit-candy-donut": "/assets/pixellab/units/candy-donut.png",
  "unit-candy-choco-engineer":
    "/assets/pixellab/units/candy-choco-engineer.png",
  "terrain-grass-1": "/assets/pixellab/terrain/grass-1.png",
  "terrain-grass-2": "/assets/pixellab/terrain/grass-2.png",
  "terrain-grass-3": "/assets/pixellab/terrain/grass-3.png",
  "terrain-grass-4": "/assets/pixellab/terrain/grass-4.png",
  "terrain-mountain-1": "/assets/pixellab/terrain/mountain-1.png",
  "terrain-mountain-2": "/assets/pixellab/terrain/mountain-2.png",
  "terrain-mountain-3": "/assets/pixellab/terrain/mountain-3.png",
  "terrain-ore": "/assets/pixellab/terrain/ore.png",
  "terrain-fruit": "/assets/pixellab/terrain/fruit.png",
  "terrain-forest-1": "/assets/pixellab/terrain/forest-1.png",
  "terrain-forest-2": "/assets/pixellab/terrain/forest-2.png",
  "terrain-forest-3": "/assets/pixellab/terrain/forest-3.png",
  "terrain-forest-4": "/assets/pixellab/terrain/forest-4.png",
  "terrain-animal": "/assets/pixellab/terrain/animal.png",
  "building-village": "/assets/pixellab/buildings/village.png",
  "building-city-1": "/assets/pixellab/buildings/city-1.png",
  "building-city-3": "/assets/pixellab/buildings/city-3.png",
  "building-city-2": "/assets/pixellab/buildings/city-2.png",
  "building-mine": "/assets/pixellab/buildings/mine.png",
  "building-lumber-mill": "/assets/pixellab/buildings/lumber-mill.png",
  "building-chocolate-wall": "/assets/pixellab/buildings/chocolate-wall.png",
  "ui-star": "/assets/pixellab/ui/star.png",
  "ui-attack": "/assets/pixellab/ui/attack.png",
  "ui-tech-climbing": "/assets/pixellab/ui/tech-climbing.png",
  "ui-tech-riding": "/assets/pixellab/ui/tech-riding.png",
  "ui-tech-hunting": "/assets/pixellab/ui/tech-hunting.png",
  "ui-tech-organization": "/assets/pixellab/ui/tech-organization.png",
  "ui-tech-mining": "/assets/pixellab/ui/tech-mining.png",
  "ui-tech-archery": "/assets/pixellab/ui/tech-archery.png",
  "ui-tech-strategy": "/assets/pixellab/ui/tech-strategy.png",
  "ui-tech-forestry": "/assets/pixellab/ui/tech-forestry.png",
  "ui-tech-mathematics": "/assets/pixellab/ui/tech-mathematics.png",
  "ui-reward-workshop": "/assets/pixellab/ui/reward-workshop.png",
  "ui-reward-survey": "/assets/pixellab/ui/reward-survey.png",
  "ui-reward-resources": "/assets/pixellab/ui/reward-resources.png",
  "ui-reward-city-wall": "/assets/pixellab/ui/reward-city-wall.png",
  "ui-faction-candy-badge": "/assets/pixellab/ui/faction-candy-badge.png",
  "ui-action-kamikaze-roll": "/assets/pixellab/ui/action-kamikaze-roll.png",
  "ui-action-candify": "/assets/pixellab/ui/action-candify.png",
  "ui-action-build-chocolate-wall":
    "/assets/pixellab/ui/action-build-chocolate-wall.png",
  "ui-action-choose-candify-city":
    "/assets/pixellab/ui/action-choose-candify-city.png",
  "ui-faction-candy-hero": "/assets/pixellab/ui/faction-candy-hero.png",
  "ui-faction-hero": "/assets/pixellab/ui/faction-hero.png",
};

export interface AcceptedArtAttachment {
  readonly projectileOrigin?: { readonly x: number; readonly y: number };
}

export const ACCEPTED_ART_ATTACHMENTS: Readonly<
  Record<string, AcceptedArtAttachment>
> = {
  "unit-archer": { projectileOrigin: { x: 0.7, y: 0.37 } },
  "unit-candy-gumball-guard": { projectileOrigin: { x: 0.6523, y: 0.5156 } },
};

export const FACTION_HERO_URL = ACCEPTED_ART_URLS["ui-faction-hero"] ?? null;
export const FACTION_HERO_URLS = Object.freeze({
  ORIGINAL: ACCEPTED_ART_URLS["ui-faction-hero"] ?? null,
  CANDY: ACCEPTED_ART_URLS["ui-faction-candy-hero"] ?? null,
});
export const FACTION_BADGE_URLS = Object.freeze({
  ORIGINAL: null,
  CANDY: ACCEPTED_ART_URLS["ui-faction-candy-badge"] ?? null,
});
export const CANDY_ACTION_ART_URLS = Object.freeze({
  KAMIKAZE_ROLL: ACCEPTED_ART_URLS["ui-action-kamikaze-roll"] ?? null,
  BUILD_CHOCOLATE_WALL:
    ACCEPTED_ART_URLS["ui-action-build-chocolate-wall"] ?? null,
  CANDIFY: ACCEPTED_ART_URLS["ui-action-candify"] ?? null,
  CHOOSE_CANDIFY_CITY:
    ACCEPTED_ART_URLS["ui-action-choose-candify-city"] ?? null,
});
